// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/webitel/option.proto

package webitel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_CREATE Action = 0
	Action_ACTION_READ   Action = 1
	Action_ACTION_UPDATE Action = 2
	Action_ACTION_DELETE Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_CREATE",
		1: "ACTION_READ",
		2: "ACTION_UPDATE",
		3: "ACTION_DELETE",
	}
	Action_value = map[string]int32{
		"ACTION_CREATE": 0,
		"ACTION_READ":   1,
		"ACTION_UPDATE": 2,
		"ACTION_DELETE": 3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_webitel_option_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_webitel_option_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_webitel_option_proto_rawDescGZIP(), []int{0}
}

var file_proto_webitel_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "option.objclass",
		Tag:           "bytes,50001,opt,name=objclass",
		Filename:      "proto/webitel/option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50002,
		Name:          "option.additional_license",
		Tag:           "bytes,50002,rep,name=additional_license",
		Filename:      "proto/webitel/option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Action)(nil),
		Field:         50002,
		Name:          "option.access",
		Tag:           "varint,50002,opt,name=access,enum=option.Action",
		Filename:      "proto/webitel/option.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string objclass = 50001;
	E_Objclass = &file_proto_webitel_option_proto_extTypes[0]
	// repeated string additional_license = 50002;
	E_AdditionalLicense = &file_proto_webitel_option_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional option.Action access = 50002;
	E_Access = &file_proto_webitel_option_proto_extTypes[2]
)

var File_proto_webitel_option_proto protoreflect.FileDescriptor

const file_proto_webitel_option_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/webitel/option.proto\x12\x06option\x1a google/protobuf/descriptor.proto*R\n" +
	"\x06Action\x12\x11\n" +
	"\rACTION_CREATE\x10\x00\x12\x0f\n" +
	"\vACTION_READ\x10\x01\x12\x11\n" +
	"\rACTION_UPDATE\x10\x02\x12\x11\n" +
	"\rACTION_DELETE\x10\x03:=\n" +
	"\bobjclass\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\tR\bobjclass:P\n" +
	"\x12additional_license\x12\x1f.google.protobuf.ServiceOptions\x18҆\x03 \x03(\tR\x11additionalLicense:H\n" +
	"\x06access\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\x0e2\x0e.option.ActionR\x06accessB\xab\x01\n" +
	"\n" +
	"com.optionB\vOptionProtoP\x01ZXgithub.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel;webitel\xa2\x02\x03OXX\xaa\x02\x06Option\xca\x02\x06Option\xe2\x02\x12Option\\GPBMetadata\xea\x02\x06Optionb\x06proto3"

var (
	file_proto_webitel_option_proto_rawDescOnce sync.Once
	file_proto_webitel_option_proto_rawDescData []byte
)

func file_proto_webitel_option_proto_rawDescGZIP() []byte {
	file_proto_webitel_option_proto_rawDescOnce.Do(func() {
		file_proto_webitel_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_webitel_option_proto_rawDesc), len(file_proto_webitel_option_proto_rawDesc)))
	})
	return file_proto_webitel_option_proto_rawDescData
}

var file_proto_webitel_option_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_webitel_option_proto_goTypes = []any{
	(Action)(0),                         // 0: option.Action
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
}
var file_proto_webitel_option_proto_depIdxs = []int32{
	1, // 0: option.objclass:extendee -> google.protobuf.ServiceOptions
	1, // 1: option.additional_license:extendee -> google.protobuf.ServiceOptions
	2, // 2: option.access:extendee -> google.protobuf.MethodOptions
	0, // 3: option.access:type_name -> option.Action
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_webitel_option_proto_init() }
func file_proto_webitel_option_proto_init() {
	if File_proto_webitel_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_webitel_option_proto_rawDesc), len(file_proto_webitel_option_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_proto_webitel_option_proto_goTypes,
		DependencyIndexes: file_proto_webitel_option_proto_depIdxs,
		EnumInfos:         file_proto_webitel_option_proto_enumTypes,
		ExtensionInfos:    file_proto_webitel_option_proto_extTypes,
	}.Build()
	File_proto_webitel_option_proto = out.File
	file_proto_webitel_option_proto_goTypes = nil
	file_proto_webitel_option_proto_depIdxs = nil
}
