// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: service/indexing.proto

package servicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Indexing_ResolveSpaceEmbedding_FullMethodName = "/webitel.kb.service.Indexing/ResolveSpaceEmbedding"
)

// IndexingClient is the client API for Indexing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Indexing serves the knowledge base indexer worker. Service to service: no
// objclass, no HTTP bindings, a service token instead of a user session.
type IndexingClient interface {
	// ResolveSpaceEmbedding returns the embedding model of a space with its credential.
	ResolveSpaceEmbedding(ctx context.Context, in *ResolveSpaceEmbeddingRequest, opts ...grpc.CallOption) (*SpaceEmbedding, error)
}

type indexingClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexingClient(cc grpc.ClientConnInterface) IndexingClient {
	return &indexingClient{cc}
}

func (c *indexingClient) ResolveSpaceEmbedding(ctx context.Context, in *ResolveSpaceEmbeddingRequest, opts ...grpc.CallOption) (*SpaceEmbedding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceEmbedding)
	err := c.cc.Invoke(ctx, Indexing_ResolveSpaceEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexingServer is the server API for Indexing service.
// All implementations must embed UnimplementedIndexingServer
// for forward compatibility.
//
// Indexing serves the knowledge base indexer worker. Service to service: no
// objclass, no HTTP bindings, a service token instead of a user session.
type IndexingServer interface {
	// ResolveSpaceEmbedding returns the embedding model of a space with its credential.
	ResolveSpaceEmbedding(context.Context, *ResolveSpaceEmbeddingRequest) (*SpaceEmbedding, error)
	mustEmbedUnimplementedIndexingServer()
}

// UnimplementedIndexingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexingServer struct{}

func (UnimplementedIndexingServer) ResolveSpaceEmbedding(context.Context, *ResolveSpaceEmbeddingRequest) (*SpaceEmbedding, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveSpaceEmbedding not implemented")
}
func (UnimplementedIndexingServer) mustEmbedUnimplementedIndexingServer() {}
func (UnimplementedIndexingServer) testEmbeddedByValue()                  {}

// UnsafeIndexingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexingServer will
// result in compilation errors.
type UnsafeIndexingServer interface {
	mustEmbedUnimplementedIndexingServer()
}

func RegisterIndexingServer(s grpc.ServiceRegistrar, srv IndexingServer) {
	// If the following call pancis, it indicates UnimplementedIndexingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Indexing_ServiceDesc, srv)
}

func _Indexing_ResolveSpaceEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSpaceEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexingServer).ResolveSpaceEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Indexing_ResolveSpaceEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexingServer).ResolveSpaceEmbedding(ctx, req.(*ResolveSpaceEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Indexing_ServiceDesc is the grpc.ServiceDesc for Indexing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Indexing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webitel.kb.service.Indexing",
	HandlerType: (*IndexingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveSpaceEmbedding",
			Handler:    _Indexing_ResolveSpaceEmbedding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/indexing.proto",
}
