// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: article.proto

package kb

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Article is the article read model.
type Article struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the article.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning domain id.
	DomainId int64 `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// Space the article belongs to.
	Space *Lookup `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
	// Parent article id; 0 for a top-level article.
	ParentId int64 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Hierarchy depth (1..5).
	Depth int32 `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	// Article type.
	Type ArticleType `protobuf:"varint,6,opt,name=type,proto3,enum=webitel.kb.ArticleType" json:"type,omitempty"`
	// Current subject (mirrors the published version).
	Subject string `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	// Article tags.
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// Lifecycle state.
	State ArticleState `protobuf:"varint,9,opt,name=state,proto3,enum=webitel.kb.ArticleState" json:"state,omitempty"`
	// Indexing state.
	IndexState IndexState `protobuf:"varint,10,opt,name=index_state,json=indexState,proto3,enum=webitel.kb.IndexState" json:"index_state,omitempty"`
	// Published version id; 0 if not yet published.
	PublishedVersionId int64 `protobuf:"varint,11,opt,name=published_version_id,json=publishedVersionId,proto3" json:"published_version_id,omitempty"`
	// Optimistic-lock counter.
	Ver int32 `protobuf:"varint,12,opt,name=ver,proto3" json:"ver,omitempty"`
	// CreatedAt timestamp (epoch ms).
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt timestamp (epoch ms).
	UpdatedAt int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// User who created the article.
	CreatedBy *Lookup `protobuf:"bytes,22,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// User who last updated the article.
	UpdatedBy *Lookup `protobuf:"bytes,23,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// Concurrency token encoding id and ver.
	Etag          string `protobuf:"bytes,30,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *Article) GetSpace() *Lookup {
	if x != nil {
		return x.Space
	}
	return nil
}

func (x *Article) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Article) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Article) GetType() ArticleType {
	if x != nil {
		return x.Type
	}
	return ArticleType_ARTICLE_TYPE_UNSPECIFIED
}

func (x *Article) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Article) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Article) GetState() ArticleState {
	if x != nil {
		return x.State
	}
	return ArticleState_ARTICLE_STATE_UNSPECIFIED
}

func (x *Article) GetIndexState() IndexState {
	if x != nil {
		return x.IndexState
	}
	return IndexState_INDEX_STATE_UNSPECIFIED
}

func (x *Article) GetPublishedVersionId() int64 {
	if x != nil {
		return x.PublishedVersionId
	}
	return 0
}

func (x *Article) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *Article) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Article) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Article) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Article) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *Article) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// InputArticle carries the writable fields of an article and its body.
type InputArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target space.
	SpaceId int64 `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Parent article id; 0 for a top-level article.
	ParentId int64 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Article type.
	Type ArticleType `protobuf:"varint,3,opt,name=type,proto3,enum=webitel.kb.ArticleType" json:"type,omitempty"`
	// Article subject.
	Subject string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	// Article tags.
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Lifecycle state.
	State ArticleState `protobuf:"varint,6,opt,name=state,proto3,enum=webitel.kb.ArticleState" json:"state,omitempty"`
	// Editor document; serialized server-side to markdown/plaintext/tsvector.
	BodyRichText  *structpb.Struct `protobuf:"bytes,7,opt,name=body_rich_text,json=bodyRichText,proto3" json:"body_rich_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputArticle) Reset() {
	*x = InputArticle{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputArticle) ProtoMessage() {}

func (x *InputArticle) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputArticle.ProtoReflect.Descriptor instead.
func (*InputArticle) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *InputArticle) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *InputArticle) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *InputArticle) GetType() ArticleType {
	if x != nil {
		return x.Type
	}
	return ArticleType_ARTICLE_TYPE_UNSPECIFIED
}

func (x *InputArticle) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InputArticle) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InputArticle) GetState() ArticleState {
	if x != nil {
		return x.State
	}
	return ArticleState_ARTICLE_STATE_UNSPECIFIED
}

func (x *InputArticle) GetBodyRichText() *structpb.Struct {
	if x != nil {
		return x.BodyRichText
	}
	return nil
}

// ListArticlesRequest parameters and filters.
type ListArticlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page size.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Page number (1-based).
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Optional subject search.
	Q string `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	// Space to list within.
	SpaceId int64 `protobuf:"varint,4,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Optional tag filter.
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Optional state filter.
	State ArticleState `protobuf:"varint,6,opt,name=state,proto3,enum=webitel.kb.ArticleState" json:"state,omitempty"`
	// Optional type filter.
	Type ArticleType `protobuf:"varint,7,opt,name=type,proto3,enum=webitel.kb.ArticleType" json:"type,omitempty"`
	// Sorting criteria (e.g. field:asc).
	Sort string `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	// Set of fields to return.
	Fields        []string `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *ListArticlesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListArticlesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListArticlesRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *ListArticlesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListArticlesRequest) GetState() ArticleState {
	if x != nil {
		return x.State
	}
	return ArticleState_ARTICLE_STATE_UNSPECIFIED
}

func (x *ListArticlesRequest) GetType() ArticleType {
	if x != nil {
		return x.Type
	}
	return ArticleType_ARTICLE_TYPE_UNSPECIFIED
}

func (x *ListArticlesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListArticlesRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ArticleList is a page of articles.
type ArticleList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Articles on this page.
	Items []*Article `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether a next page exists.
	Next          bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleList) Reset() {
	*x = ArticleList{}
	mi := &file_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleList) ProtoMessage() {}

func (x *ArticleList) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleList.ProtoReflect.Descriptor instead.
func (*ArticleList) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleList) GetItems() []*Article {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ArticleList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// LocateArticleRequest selects an article by etag.
type LocateArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Concurrency token / locator.
	Etag          string `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateArticleRequest) Reset() {
	*x = LocateArticleRequest{}
	mi := &file_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateArticleRequest) ProtoMessage() {}

func (x *LocateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateArticleRequest.ProtoReflect.Descriptor instead.
func (*LocateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{4}
}

func (x *LocateArticleRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// CreateArticleRequest wraps the article to create.
type CreateArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article fields.
	Input         *InputArticle `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{5}
}

func (x *CreateArticleRequest) GetInput() *InputArticle {
	if x != nil {
		return x.Input
	}
	return nil
}

// UpdateArticleRequest wraps the etag and updated fields.
type UpdateArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Concurrency token of the article to update.
	Etag string `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	// Updated article fields.
	Input         *InputArticle `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateArticleRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *UpdateArticleRequest) GetInput() *InputArticle {
	if x != nil {
		return x.Input
	}
	return nil
}

// DeleteArticleRequest selects an article to delete.
type DeleteArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Concurrency token of the article to delete.
	Etag          string `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// MoveArticleRequest reparents an article.
type MoveArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Concurrency token of the article to move.
	Etag string `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	// New parent id; 0 to move to top level.
	NewParentId   int64 `protobuf:"varint,2,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveArticleRequest) Reset() {
	*x = MoveArticleRequest{}
	mi := &file_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveArticleRequest) ProtoMessage() {}

func (x *MoveArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveArticleRequest.ProtoReflect.Descriptor instead.
func (*MoveArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{8}
}

func (x *MoveArticleRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *MoveArticleRequest) GetNewParentId() int64 {
	if x != nil {
		return x.NewParentId
	}
	return 0
}

// ListChildrenRequest selects the parent article.
type ListChildrenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent article id.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChildrenRequest) Reset() {
	*x = ListChildrenRequest{}
	mi := &file_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChildrenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChildrenRequest) ProtoMessage() {}

func (x *ListChildrenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChildrenRequest.ProtoReflect.Descriptor instead.
func (*ListChildrenRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{9}
}

func (x *ListChildrenRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListAncestorsRequest selects the article whose ancestors are requested.
type ListAncestorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article id.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAncestorsRequest) Reset() {
	*x = ListAncestorsRequest{}
	mi := &file_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAncestorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAncestorsRequest) ProtoMessage() {}

func (x *ListAncestorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAncestorsRequest.ProtoReflect.Descriptor instead.
func (*ListAncestorsRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{10}
}

func (x *ListAncestorsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetTreeRequest selects the space whose tree is requested.
type GetTreeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space id.
	SpaceId       int64 `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeRequest) Reset() {
	*x = GetTreeRequest{}
	mi := &file_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRequest) ProtoMessage() {}

func (x *GetTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRequest.ProtoReflect.Descriptor instead.
func (*GetTreeRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{11}
}

func (x *GetTreeRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

// GetTreeResponse returns the root nodes of the space tree.
type GetTreeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root-level tree nodes.
	Nodes         []*TreeNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeResponse) Reset() {
	*x = GetTreeResponse{}
	mi := &file_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeResponse) ProtoMessage() {}

func (x *GetTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeResponse.ProtoReflect.Descriptor instead.
func (*GetTreeResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{12}
}

func (x *GetTreeResponse) GetNodes() []*TreeNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_article_proto protoreflect.FileDescriptor

const file_article_proto_rawDesc = "" +
	"\n" +
	"\rarticle.proto\x12\n" +
	"webitel.kb\x1a\fcommon.proto\x1a\rgeneral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1aproto/webitel/option.proto\"\xca\x04\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12%\n" +
	"\x05space\x18\x03 \x01(\v2\x0f.general.LookupR\x05space\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\x12+\n" +
	"\x04type\x18\x06 \x01(\x0e2\x17.webitel.kb.ArticleTypeR\x04type\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12.\n" +
	"\x05state\x18\t \x01(\x0e2\x18.webitel.kb.ArticleStateR\x05state\x127\n" +
	"\vindex_state\x18\n" +
	" \x01(\x0e2\x16.webitel.kb.IndexStateR\n" +
	"indexState\x120\n" +
	"\x14published_version_id\x18\v \x01(\x03R\x12publishedVersionId\x12\x10\n" +
	"\x03ver\x18\f \x01(\x05R\x03ver\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x16 \x01(\v2\x0f.general.LookupR\tcreatedBy\x12.\n" +
	"\n" +
	"updated_by\x18\x17 \x01(\v2\x0f.general.LookupR\tupdatedBy\x12\x12\n" +
	"\x04etag\x18\x1e \x01(\tR\x04etag\"\x90\x02\n" +
	"\fInputArticle\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\x03R\aspaceId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.webitel.kb.ArticleTypeR\x04type\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12.\n" +
	"\x05state\x18\x06 \x01(\x0e2\x18.webitel.kb.ArticleStateR\x05state\x12=\n" +
	"\x0ebody_rich_text\x18\a \x01(\v2\x17.google.protobuf.StructR\fbodyRichText\"\x83\x02\n" +
	"\x13ListArticlesRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x19\n" +
	"\bspace_id\x18\x04 \x01(\x03R\aspaceId\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12.\n" +
	"\x05state\x18\x06 \x01(\x0e2\x18.webitel.kb.ArticleStateR\x05state\x12+\n" +
	"\x04type\x18\a \x01(\x0e2\x17.webitel.kb.ArticleTypeR\x04type\x12\x12\n" +
	"\x04sort\x18\b \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\t \x03(\tR\x06fields\"L\n" +
	"\vArticleList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.webitel.kb.ArticleR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\"*\n" +
	"\x14LocateArticleRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\"F\n" +
	"\x14CreateArticleRequest\x12.\n" +
	"\x05input\x18\x01 \x01(\v2\x18.webitel.kb.InputArticleR\x05input\"Z\n" +
	"\x14UpdateArticleRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12.\n" +
	"\x05input\x18\x02 \x01(\v2\x18.webitel.kb.InputArticleR\x05input\"*\n" +
	"\x14DeleteArticleRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\"L\n" +
	"\x12MoveArticleRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12\"\n" +
	"\rnew_parent_id\x18\x02 \x01(\x03R\vnewParentId\"%\n" +
	"\x13ListChildrenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\x14ListAncestorsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"+\n" +
	"\x0eGetTreeRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\x03R\aspaceId\"=\n" +
	"\x0fGetTreeResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.webitel.kb.TreeNodeR\x05nodes2\xa7\b\n" +
	"\bArticles\x12e\n" +
	"\fListArticles\x12\x1f.webitel.kb.ListArticlesRequest\x1a\x17.webitel.kb.ArticleList\"\x1b\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/kb/articles\x12j\n" +
	"\rLocateArticle\x12 .webitel.kb.LocateArticleRequest\x1a\x13.webitel.kb.Article\"\"\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/kb/articles/{etag}\x12j\n" +
	"\rCreateArticle\x12 .webitel.kb.CreateArticleRequest\x1a\x13.webitel.kb.Article\"\"\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x18:\x05input\"\x0f/v1/kb/articles\x12\x92\x01\n" +
	"\rUpdateArticle\x12 .webitel.kb.UpdateArticleRequest\x1a\x13.webitel.kb.Article\"J\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02@:\x05inputZ\x1f:\x05input2\x16/v1/kb/articles/{etag}\x1a\x16/v1/kb/articles/{etag}\x12j\n" +
	"\rDeleteArticle\x12 .webitel.kb.DeleteArticleRequest\x1a\x13.webitel.kb.Article\"\"\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x18*\x16/v1/kb/articles/{etag}\x12n\n" +
	"\vMoveArticle\x12\x1e.webitel.kb.MoveArticleRequest\x1a\x13.webitel.kb.Article\"*\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/kb/articles/{etag}/move\x12s\n" +
	"\fListChildren\x12\x1f.webitel.kb.ListChildrenRequest\x1a\x17.webitel.kb.ArticleList\")\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/kb/articles/{id}/children\x12v\n" +
	"\rListAncestors\x12 .webitel.kb.ListAncestorsRequest\x1a\x17.webitel.kb.ArticleList\"*\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02 \x12\x1e/v1/kb/articles/{id}/ancestors\x12m\n" +
	"\aGetTree\x12\x1a.webitel.kb.GetTreeRequest\x1a\x1b.webitel.kb.GetTreeResponse\")\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/kb/spaces/{space_id}/tree\x1a\x0f\x8a\xb5\x18\vkb_articlesB\x90\x01\n" +
	"\x0ecom.webitel.kbB\fArticleProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData []byte
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)))
	})
	return file_article_proto_rawDescData
}

var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_article_proto_goTypes = []any{
	(*Article)(nil),              // 0: webitel.kb.Article
	(*InputArticle)(nil),         // 1: webitel.kb.InputArticle
	(*ListArticlesRequest)(nil),  // 2: webitel.kb.ListArticlesRequest
	(*ArticleList)(nil),          // 3: webitel.kb.ArticleList
	(*LocateArticleRequest)(nil), // 4: webitel.kb.LocateArticleRequest
	(*CreateArticleRequest)(nil), // 5: webitel.kb.CreateArticleRequest
	(*UpdateArticleRequest)(nil), // 6: webitel.kb.UpdateArticleRequest
	(*DeleteArticleRequest)(nil), // 7: webitel.kb.DeleteArticleRequest
	(*MoveArticleRequest)(nil),   // 8: webitel.kb.MoveArticleRequest
	(*ListChildrenRequest)(nil),  // 9: webitel.kb.ListChildrenRequest
	(*ListAncestorsRequest)(nil), // 10: webitel.kb.ListAncestorsRequest
	(*GetTreeRequest)(nil),       // 11: webitel.kb.GetTreeRequest
	(*GetTreeResponse)(nil),      // 12: webitel.kb.GetTreeResponse
	(*Lookup)(nil),               // 13: general.Lookup
	(ArticleType)(0),             // 14: webitel.kb.ArticleType
	(ArticleState)(0),            // 15: webitel.kb.ArticleState
	(IndexState)(0),              // 16: webitel.kb.IndexState
	(*structpb.Struct)(nil),      // 17: google.protobuf.Struct
	(*TreeNode)(nil),             // 18: webitel.kb.TreeNode
}
var file_article_proto_depIdxs = []int32{
	13, // 0: webitel.kb.Article.space:type_name -> general.Lookup
	14, // 1: webitel.kb.Article.type:type_name -> webitel.kb.ArticleType
	15, // 2: webitel.kb.Article.state:type_name -> webitel.kb.ArticleState
	16, // 3: webitel.kb.Article.index_state:type_name -> webitel.kb.IndexState
	13, // 4: webitel.kb.Article.created_by:type_name -> general.Lookup
	13, // 5: webitel.kb.Article.updated_by:type_name -> general.Lookup
	14, // 6: webitel.kb.InputArticle.type:type_name -> webitel.kb.ArticleType
	15, // 7: webitel.kb.InputArticle.state:type_name -> webitel.kb.ArticleState
	17, // 8: webitel.kb.InputArticle.body_rich_text:type_name -> google.protobuf.Struct
	15, // 9: webitel.kb.ListArticlesRequest.state:type_name -> webitel.kb.ArticleState
	14, // 10: webitel.kb.ListArticlesRequest.type:type_name -> webitel.kb.ArticleType
	0,  // 11: webitel.kb.ArticleList.items:type_name -> webitel.kb.Article
	1,  // 12: webitel.kb.CreateArticleRequest.input:type_name -> webitel.kb.InputArticle
	1,  // 13: webitel.kb.UpdateArticleRequest.input:type_name -> webitel.kb.InputArticle
	18, // 14: webitel.kb.GetTreeResponse.nodes:type_name -> webitel.kb.TreeNode
	2,  // 15: webitel.kb.Articles.ListArticles:input_type -> webitel.kb.ListArticlesRequest
	4,  // 16: webitel.kb.Articles.LocateArticle:input_type -> webitel.kb.LocateArticleRequest
	5,  // 17: webitel.kb.Articles.CreateArticle:input_type -> webitel.kb.CreateArticleRequest
	6,  // 18: webitel.kb.Articles.UpdateArticle:input_type -> webitel.kb.UpdateArticleRequest
	7,  // 19: webitel.kb.Articles.DeleteArticle:input_type -> webitel.kb.DeleteArticleRequest
	8,  // 20: webitel.kb.Articles.MoveArticle:input_type -> webitel.kb.MoveArticleRequest
	9,  // 21: webitel.kb.Articles.ListChildren:input_type -> webitel.kb.ListChildrenRequest
	10, // 22: webitel.kb.Articles.ListAncestors:input_type -> webitel.kb.ListAncestorsRequest
	11, // 23: webitel.kb.Articles.GetTree:input_type -> webitel.kb.GetTreeRequest
	3,  // 24: webitel.kb.Articles.ListArticles:output_type -> webitel.kb.ArticleList
	0,  // 25: webitel.kb.Articles.LocateArticle:output_type -> webitel.kb.Article
	0,  // 26: webitel.kb.Articles.CreateArticle:output_type -> webitel.kb.Article
	0,  // 27: webitel.kb.Articles.UpdateArticle:output_type -> webitel.kb.Article
	0,  // 28: webitel.kb.Articles.DeleteArticle:output_type -> webitel.kb.Article
	0,  // 29: webitel.kb.Articles.MoveArticle:output_type -> webitel.kb.Article
	3,  // 30: webitel.kb.Articles.ListChildren:output_type -> webitel.kb.ArticleList
	3,  // 31: webitel.kb.Articles.ListAncestors:output_type -> webitel.kb.ArticleList
	12, // 32: webitel.kb.Articles.GetTree:output_type -> webitel.kb.GetTreeResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	file_common_proto_init()
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
