// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: attachment.proto

package kb

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attachment is a file bound to an article.
type Attachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the attachment.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning article id.
	ArticleId int64 `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Pointer into Webitel Storage.
	StorageUri string `protobuf:"bytes,3,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	// Original file name.
	Filename string `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	// MIME type.
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// File size in bytes.
	SizeBytes int64 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// CreatedAt timestamp (epoch ms).
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// User who uploaded the attachment.
	CreatedBy     *Lookup `protobuf:"bytes,22,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Attachment) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *Attachment) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Attachment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Attachment) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

// ListAttachmentsRequest selects the article.
type ListAttachmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning article id.
	ArticleId     int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsRequest) Reset() {
	*x = ListAttachmentsRequest{}
	mi := &file_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsRequest) ProtoMessage() {}

func (x *ListAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *ListAttachmentsRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

// AttachmentList is a list of attachments.
type AttachmentList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attachments of the article.
	Items []*Attachment `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether a next page exists.
	Next          bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentList) Reset() {
	*x = AttachmentList{}
	mi := &file_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentList) ProtoMessage() {}

func (x *AttachmentList) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentList.ProtoReflect.Descriptor instead.
func (*AttachmentList) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *AttachmentList) GetItems() []*Attachment {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AttachmentList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// CreateAttachmentRequest uploads a file for an article.
type CreateAttachmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning article id.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Original file name.
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	// MIME type.
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Raw file content.
	Content       []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttachmentRequest) Reset() {
	*x = CreateAttachmentRequest{}
	mi := &file_attachment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentRequest) ProtoMessage() {}

func (x *CreateAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAttachmentRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *CreateAttachmentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateAttachmentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CreateAttachmentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// DeleteAttachmentRequest selects an attachment to delete.
type DeleteAttachmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning article id.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Attachment id.
	Id            int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentRequest) Reset() {
	*x = DeleteAttachmentRequest{}
	mi := &file_attachment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentRequest) ProtoMessage() {}

func (x *DeleteAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAttachmentRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *DeleteAttachmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_attachment_proto protoreflect.FileDescriptor

const file_attachment_proto_rawDesc = "" +
	"\n" +
	"\x10attachment.proto\x12\n" +
	"webitel.kb\x1a\rgeneral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"\x83\x02\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\x12\x1f\n" +
	"\vstorage_uri\x18\x03 \x01(\tR\n" +
	"storageUri\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x16 \x01(\v2\x0f.general.LookupR\tcreatedBy\"7\n" +
	"\x16ListAttachmentsRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\"R\n" +
	"\x0eAttachmentList\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.webitel.kb.AttachmentR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\"\x8b\x01\n" +
	"\x17CreateAttachmentRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"H\n" +
	"\x17DeleteAttachmentRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id2\xb7\x03\n" +
	"\vAttachments\x12\x84\x01\n" +
	"\x0fListAttachments\x12\".webitel.kb.ListAttachmentsRequest\x1a\x1a.webitel.kb.AttachmentList\"1\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02'\x12%/v1/articles/{article_id}/attachments\x12\x85\x01\n" +
	"\x10CreateAttachment\x12#.webitel.kb.CreateAttachmentRequest\x1a\x16.webitel.kb.Attachment\"4\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/articles/{article_id}/attachments\x12\x87\x01\n" +
	"\x10DeleteAttachment\x12#.webitel.kb.DeleteAttachmentRequest\x1a\x16.webitel.kb.Attachment\"6\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02,**/v1/articles/{article_id}/attachments/{id}\x1a\x0f\x8a\xb5\x18\vkb_articlesB\x93\x01\n" +
	"\x0ecom.webitel.kbB\x0fAttachmentProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_attachment_proto_rawDescOnce sync.Once
	file_attachment_proto_rawDescData []byte
)

func file_attachment_proto_rawDescGZIP() []byte {
	file_attachment_proto_rawDescOnce.Do(func() {
		file_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)))
	})
	return file_attachment_proto_rawDescData
}

var file_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_attachment_proto_goTypes = []any{
	(*Attachment)(nil),              // 0: webitel.kb.Attachment
	(*ListAttachmentsRequest)(nil),  // 1: webitel.kb.ListAttachmentsRequest
	(*AttachmentList)(nil),          // 2: webitel.kb.AttachmentList
	(*CreateAttachmentRequest)(nil), // 3: webitel.kb.CreateAttachmentRequest
	(*DeleteAttachmentRequest)(nil), // 4: webitel.kb.DeleteAttachmentRequest
	(*Lookup)(nil),                  // 5: general.Lookup
}
var file_attachment_proto_depIdxs = []int32{
	5, // 0: webitel.kb.Attachment.created_by:type_name -> general.Lookup
	0, // 1: webitel.kb.AttachmentList.items:type_name -> webitel.kb.Attachment
	1, // 2: webitel.kb.Attachments.ListAttachments:input_type -> webitel.kb.ListAttachmentsRequest
	3, // 3: webitel.kb.Attachments.CreateAttachment:input_type -> webitel.kb.CreateAttachmentRequest
	4, // 4: webitel.kb.Attachments.DeleteAttachment:input_type -> webitel.kb.DeleteAttachmentRequest
	2, // 5: webitel.kb.Attachments.ListAttachments:output_type -> webitel.kb.AttachmentList
	0, // 6: webitel.kb.Attachments.CreateAttachment:output_type -> webitel.kb.Attachment
	0, // 7: webitel.kb.Attachments.DeleteAttachment:output_type -> webitel.kb.Attachment
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_attachment_proto_init() }
func file_attachment_proto_init() {
	if File_attachment_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attachment_proto_goTypes,
		DependencyIndexes: file_attachment_proto_depIdxs,
		MessageInfos:      file_attachment_proto_msgTypes,
	}.Build()
	File_attachment_proto = out.File
	file_attachment_proto_goTypes = nil
	file_attachment_proto_depIdxs = nil
}
