// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common.proto

package kb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Article type.
type ArticleType int32

const (
	ArticleType_ARTICLE_TYPE_UNSPECIFIED ArticleType = 0
	ArticleType_ARTICLE                  ArticleType = 1
	ArticleType_FAQ                      ArticleType = 2
)

// Enum value maps for ArticleType.
var (
	ArticleType_name = map[int32]string{
		0: "ARTICLE_TYPE_UNSPECIFIED",
		1: "ARTICLE",
		2: "FAQ",
	}
	ArticleType_value = map[string]int32{
		"ARTICLE_TYPE_UNSPECIFIED": 0,
		"ARTICLE":                  1,
		"FAQ":                      2,
	}
)

func (x ArticleType) Enum() *ArticleType {
	p := new(ArticleType)
	*p = x
	return p
}

func (x ArticleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ArticleType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ArticleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleType.Descriptor instead.
func (ArticleType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Article lifecycle state.
type ArticleState int32

const (
	ArticleState_ARTICLE_STATE_UNSPECIFIED ArticleState = 0
	ArticleState_DRAFT                     ArticleState = 1
	ArticleState_ACTIVE                    ArticleState = 2
	ArticleState_INACTIVE                  ArticleState = 3
)

// Enum value maps for ArticleState.
var (
	ArticleState_name = map[int32]string{
		0: "ARTICLE_STATE_UNSPECIFIED",
		1: "DRAFT",
		2: "ACTIVE",
		3: "INACTIVE",
	}
	ArticleState_value = map[string]int32{
		"ARTICLE_STATE_UNSPECIFIED": 0,
		"DRAFT":                     1,
		"ACTIVE":                    2,
		"INACTIVE":                  3,
	}
)

func (x ArticleState) Enum() *ArticleState {
	p := new(ArticleState)
	*p = x
	return p
}

func (x ArticleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ArticleState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ArticleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleState.Descriptor instead.
func (ArticleState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Article indexing state.
type IndexState int32

const (
	IndexState_INDEX_STATE_UNSPECIFIED IndexState = 0
	IndexState_PENDING                 IndexState = 1
	IndexState_INDEXING                IndexState = 2
	IndexState_INDEXED                 IndexState = 3
	IndexState_FAILED                  IndexState = 4
)

// Enum value maps for IndexState.
var (
	IndexState_name = map[int32]string{
		0: "INDEX_STATE_UNSPECIFIED",
		1: "PENDING",
		2: "INDEXING",
		3: "INDEXED",
		4: "FAILED",
	}
	IndexState_value = map[string]int32{
		"INDEX_STATE_UNSPECIFIED": 0,
		"PENDING":                 1,
		"INDEXING":                2,
		"INDEXED":                 3,
		"FAILED":                  4,
	}
)

func (x IndexState) Enum() *IndexState {
	p := new(IndexState)
	*p = x
	return p
}

func (x IndexState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (IndexState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x IndexState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexState.Descriptor instead.
func (IndexState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// ArticleSummary is a lightweight read model of an article, used by list,
// search, resolve and menu responses (no body unless inlined for FAQ menu).
type ArticleSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the article.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Space the article belongs to.
	SpaceId int64 `protobuf:"varint,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Parent article id; 0 for a top-level article.
	ParentId int64 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Hierarchy depth (1..5).
	Depth int32 `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	// Article type.
	Type ArticleType `protobuf:"varint,5,opt,name=type,proto3,enum=webitel.kb.ArticleType" json:"type,omitempty"`
	// Current subject (mirrors the published version).
	Subject string `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	// Short text excerpt for previews and search hits.
	Snippet string `protobuf:"bytes,7,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// Article tags.
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// Lifecycle state.
	State ArticleState `protobuf:"varint,9,opt,name=state,proto3,enum=webitel.kb.ArticleState" json:"state,omitempty"`
	// FAQ body inlined for menu responses; empty otherwise.
	Body string `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	// CreatedAt timestamp (epoch ms).
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt timestamp (epoch ms).
	UpdatedAt     int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleSummary) Reset() {
	*x = ArticleSummary{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleSummary) ProtoMessage() {}

func (x *ArticleSummary) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleSummary.ProtoReflect.Descriptor instead.
func (*ArticleSummary) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleSummary) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *ArticleSummary) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ArticleSummary) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *ArticleSummary) GetType() ArticleType {
	if x != nil {
		return x.Type
	}
	return ArticleType_ARTICLE_TYPE_UNSPECIFIED
}

func (x *ArticleSummary) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ArticleSummary) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *ArticleSummary) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ArticleSummary) GetState() ArticleState {
	if x != nil {
		return x.State
	}
	return ArticleState_ARTICLE_STATE_UNSPECIFIED
}

func (x *ArticleSummary) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ArticleSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ArticleSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Chunk is a contiguous slice of an article version, the unit returned by
// semantic search and consumed by downstream RAG.
type Chunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article the chunk originates from.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Article version the chunk was produced from.
	VersionId int64 `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// Ordinal position of the chunk within the version.
	ChunkIndex int32 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// Chunk text content.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Relevance score assigned by retrieval (higher is better).
	Score         float64 `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *Chunk) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *Chunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Citation is a structured source reference returned alongside retrieval
// results; rendering is up to the consumer (chips, spoken, or suppressed).
type Citation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source article id.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Source article title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Quoted snippet supporting the answer.
	Snippet string `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// Deep link to the source article.
	Url           string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Citation) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *Citation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Citation) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Citation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// TreeNode is a single node of an article hierarchy tree.
type TreeNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Article subject.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Article type.
	Type ArticleType `protobuf:"varint,3,opt,name=type,proto3,enum=webitel.kb.ArticleType" json:"type,omitempty"`
	// Hierarchy depth (1..5).
	Depth int32 `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	// Child nodes.
	Children      []*TreeNode `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *TreeNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TreeNode) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TreeNode) GetType() ArticleType {
	if x != nil {
		return x.Type
	}
	return ArticleType_ARTICLE_TYPE_UNSPECIFIED
}

func (x *TreeNode) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *TreeNode) GetChildren() []*TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\n" +
	"webitel.kb\x1a\rgeneral.proto\"\xe5\x02\n" +
	"\x0eArticleSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\x03R\aspaceId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.webitel.kb.ArticleTypeR\x04type\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x18\n" +
	"\asnippet\x18\a \x01(\tR\asnippet\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12.\n" +
	"\x05state\x18\t \x01(\x0e2\x18.webitel.kb.ArticleStateR\x05state\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\"\x96\x01\n" +
	"\x05Chunk\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x03R\tversionId\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"k\n" +
	"\bCitation\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\xa9\x01\n" +
	"\bTreeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.webitel.kb.ArticleTypeR\x04type\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\x05R\x05depth\x120\n" +
	"\bchildren\x18\x05 \x03(\v2\x14.webitel.kb.TreeNodeR\bchildren*A\n" +
	"\vArticleType\x12\x1c\n" +
	"\x18ARTICLE_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aARTICLE\x10\x01\x12\a\n" +
	"\x03FAQ\x10\x02*R\n" +
	"\fArticleState\x12\x1d\n" +
	"\x19ARTICLE_STATE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\f\n" +
	"\bINACTIVE\x10\x03*]\n" +
	"\n" +
	"IndexState\x12\x1b\n" +
	"\x17INDEX_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bINDEXING\x10\x02\x12\v\n" +
	"\aINDEXED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04B\x8f\x01\n" +
	"\x0ecom.webitel.kbB\vCommonProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(ArticleType)(0),       // 0: webitel.kb.ArticleType
	(ArticleState)(0),      // 1: webitel.kb.ArticleState
	(IndexState)(0),        // 2: webitel.kb.IndexState
	(*ArticleSummary)(nil), // 3: webitel.kb.ArticleSummary
	(*Chunk)(nil),          // 4: webitel.kb.Chunk
	(*Citation)(nil),       // 5: webitel.kb.Citation
	(*TreeNode)(nil),       // 6: webitel.kb.TreeNode
}
var file_common_proto_depIdxs = []int32{
	0, // 0: webitel.kb.ArticleSummary.type:type_name -> webitel.kb.ArticleType
	1, // 1: webitel.kb.ArticleSummary.state:type_name -> webitel.kb.ArticleState
	0, // 2: webitel.kb.TreeNode.type:type_name -> webitel.kb.ArticleType
	6, // 3: webitel.kb.TreeNode.children:type_name -> webitel.kb.TreeNode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
