// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: model.proto

package kb

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmbeddingModel is a registry entry read model (credential omitted).
type EmbeddingModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the model.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning domain id; 0 for a global (Webitel-seeded) model.
	DomainId int64 `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// Model type: "embedding" or "reranker".
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Human-readable name shown in the admin UI.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Provider key (gemini, openai, cohere, azure, bge-m3, e5, bge-reranker, byom).
	Provider string `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	// Whether the model runs self-hosted.
	IsSelfHosted bool `protobuf:"varint,6,opt,name=is_self_hosted,json=isSelfHosted,proto3" json:"is_self_hosted,omitempty"`
	// Provider model name or HuggingFace id.
	ModelRef string `protobuf:"bytes,7,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	// Embedding dimension; 0 for rerankers.
	Dimensions int32 `protobuf:"varint,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// Self-hosted / Azure / BYOM endpoint url.
	Endpoint string `protobuf:"bytes,9,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Timestamp of the last successful validation (epoch ms); 0 if never validated.
	ValidatedAt int64 `protobuf:"varint,10,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	// CreatedAt timestamp (epoch ms).
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// User who created the model.
	CreatedBy     *Lookup `protobuf:"bytes,22,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingModel) Reset() {
	*x = EmbeddingModel{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingModel) ProtoMessage() {}

func (x *EmbeddingModel) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingModel.ProtoReflect.Descriptor instead.
func (*EmbeddingModel) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmbeddingModel) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *EmbeddingModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmbeddingModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmbeddingModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmbeddingModel) GetIsSelfHosted() bool {
	if x != nil {
		return x.IsSelfHosted
	}
	return false
}

func (x *EmbeddingModel) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *EmbeddingModel) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *EmbeddingModel) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *EmbeddingModel) GetValidatedAt() int64 {
	if x != nil {
		return x.ValidatedAt
	}
	return 0
}

func (x *EmbeddingModel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EmbeddingModel) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

// InputEmbeddingModel carries the writable fields of a model.
type InputEmbeddingModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model type: "embedding" or "reranker".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Human-readable name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Provider key.
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// Whether the model runs self-hosted.
	IsSelfHosted bool `protobuf:"varint,4,opt,name=is_self_hosted,json=isSelfHosted,proto3" json:"is_self_hosted,omitempty"`
	// Provider model name or HuggingFace id.
	ModelRef string `protobuf:"bytes,5,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	// Embedding dimension; omit for rerankers.
	Dimensions int32 `protobuf:"varint,6,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// Self-hosted / Azure / BYOM endpoint url.
	Endpoint string `protobuf:"bytes,7,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Write-only provider credential; encrypted at rest, never read back.
	ApiKey        string `protobuf:"bytes,8,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputEmbeddingModel) Reset() {
	*x = InputEmbeddingModel{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputEmbeddingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEmbeddingModel) ProtoMessage() {}

func (x *InputEmbeddingModel) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEmbeddingModel.ProtoReflect.Descriptor instead.
func (*InputEmbeddingModel) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *InputEmbeddingModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InputEmbeddingModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputEmbeddingModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InputEmbeddingModel) GetIsSelfHosted() bool {
	if x != nil {
		return x.IsSelfHosted
	}
	return false
}

func (x *InputEmbeddingModel) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *InputEmbeddingModel) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *InputEmbeddingModel) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *InputEmbeddingModel) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// ListModelsRequest parameters.
type ListModelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page size.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Page number (1-based).
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Optional name search.
	Q string `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	// Optional type filter ("embedding" or "reranker").
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Sorting criteria (e.g. field:asc).
	Sort string `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	// Set of fields to return.
	Fields        []string `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListModelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListModelsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListModelsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListModelsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListModelsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// EmbeddingModelList is a page of models.
type EmbeddingModelList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Models on this page.
	Items []*EmbeddingModel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether a next page exists.
	Next          bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingModelList) Reset() {
	*x = EmbeddingModelList{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingModelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingModelList) ProtoMessage() {}

func (x *EmbeddingModelList) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingModelList.ProtoReflect.Descriptor instead.
func (*EmbeddingModelList) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *EmbeddingModelList) GetItems() []*EmbeddingModel {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *EmbeddingModelList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// LocateModelRequest selects a model by id.
type LocateModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model id.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateModelRequest) Reset() {
	*x = LocateModelRequest{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateModelRequest) ProtoMessage() {}

func (x *LocateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateModelRequest.ProtoReflect.Descriptor instead.
func (*LocateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *LocateModelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// CreateModelRequest wraps the model to create.
type CreateModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model fields.
	Input         *InputEmbeddingModel `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (x *CreateModelRequest) GetInput() *InputEmbeddingModel {
	if x != nil {
		return x.Input
	}
	return nil
}

// UpdateModelRequest wraps the model id and updated fields.
type UpdateModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Updated model fields.
	Input         *InputEmbeddingModel `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelRequest) Reset() {
	*x = UpdateModelRequest{}
	mi := &file_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelRequest) ProtoMessage() {}

func (x *UpdateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateModelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateModelRequest) GetInput() *InputEmbeddingModel {
	if x != nil {
		return x.Input
	}
	return nil
}

// DeleteModelRequest selects a model to delete.
type DeleteModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model id.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteModelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ValidateModelRequest selects a model to validate.
type ValidateModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model id.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateModelRequest) Reset() {
	*x = ValidateModelRequest{}
	mi := &file_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateModelRequest) ProtoMessage() {}

func (x *ValidateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateModelRequest.ProtoReflect.Descriptor instead.
func (*ValidateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateModelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_model_proto protoreflect.FileDescriptor

const file_model_proto_rawDesc = "" +
	"\n" +
	"\vmodel.proto\x12\n" +
	"webitel.kb\x1a\rgeneral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xf2\x02\n" +
	"\x0eEmbeddingModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12$\n" +
	"\x0eis_self_hosted\x18\x06 \x01(\bR\fisSelfHosted\x12\x1b\n" +
	"\tmodel_ref\x18\a \x01(\tR\bmodelRef\x12\x1e\n" +
	"\n" +
	"dimensions\x18\b \x01(\x05R\n" +
	"dimensions\x12\x1a\n" +
	"\bendpoint\x18\t \x01(\tR\bendpoint\x12!\n" +
	"\fvalidated_at\x18\n" +
	" \x01(\x03R\vvalidatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x16 \x01(\v2\x0f.general.LookupR\tcreatedBy\"\xf1\x01\n" +
	"\x13InputEmbeddingModel\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12$\n" +
	"\x0eis_self_hosted\x18\x04 \x01(\bR\fisSelfHosted\x12\x1b\n" +
	"\tmodel_ref\x18\x05 \x01(\tR\bmodelRef\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x06 \x01(\x05R\n" +
	"dimensions\x12\x1a\n" +
	"\bendpoint\x18\a \x01(\tR\bendpoint\x12\x17\n" +
	"\aapi_key\x18\b \x01(\tR\x06apiKey\"\x89\x01\n" +
	"\x11ListModelsRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x06 \x03(\tR\x06fields\"Z\n" +
	"\x12EmbeddingModelList\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.webitel.kb.EmbeddingModelR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\"$\n" +
	"\x12LocateModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x12CreateModelRequest\x125\n" +
	"\x05input\x18\x01 \x01(\v2\x1f.webitel.kb.InputEmbeddingModelR\x05input\"[\n" +
	"\x12UpdateModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x125\n" +
	"\x05input\x18\x02 \x01(\v2\x1f.webitel.kb.InputEmbeddingModelR\x05input\"$\n" +
	"\x12DeleteModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\x14ValidateModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xd3\x05\n" +
	"\x0fEmbeddingModels\x12f\n" +
	"\n" +
	"ListModels\x12\x1d.webitel.kb.ListModelsRequest\x1a\x1e.webitel.kb.EmbeddingModelList\"\x19\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/kb/models\x12i\n" +
	"\vLocateModel\x12\x1e.webitel.kb.LocateModelRequest\x1a\x1a.webitel.kb.EmbeddingModel\"\x1e\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/kb/models/{id}\x12k\n" +
	"\vCreateModel\x12\x1e.webitel.kb.CreateModelRequest\x1a\x1a.webitel.kb.EmbeddingModel\" \x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x16:\x05input\"\r/v1/kb/models\x12\x8d\x01\n" +
	"\vUpdateModel\x12\x1e.webitel.kb.UpdateModelRequest\x1a\x1a.webitel.kb.EmbeddingModel\"B\x90\xb5\x18\x02\x82\xd3\xe4\x93\x028:\x05inputZ\x1b:\x05input2\x12/v1/kb/models/{id}\x1a\x12/v1/kb/models/{id}\x12i\n" +
	"\vDeleteModel\x12\x1e.webitel.kb.DeleteModelRequest\x1a\x1a.webitel.kb.EmbeddingModel\"\x1e\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x14*\x12/v1/kb/models/{id}\x12v\n" +
	"\rValidateModel\x12 .webitel.kb.ValidateModelRequest\x1a\x1a.webitel.kb.EmbeddingModel\"'\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x1d\"\x1b/v1/kb/models/{id}/validate\x1a\r\x8a\xb5\x18\tkb_modelsB\x8e\x01\n" +
	"\x0ecom.webitel.kbB\n" +
	"ModelProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData []byte
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)))
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_model_proto_goTypes = []any{
	(*EmbeddingModel)(nil),       // 0: webitel.kb.EmbeddingModel
	(*InputEmbeddingModel)(nil),  // 1: webitel.kb.InputEmbeddingModel
	(*ListModelsRequest)(nil),    // 2: webitel.kb.ListModelsRequest
	(*EmbeddingModelList)(nil),   // 3: webitel.kb.EmbeddingModelList
	(*LocateModelRequest)(nil),   // 4: webitel.kb.LocateModelRequest
	(*CreateModelRequest)(nil),   // 5: webitel.kb.CreateModelRequest
	(*UpdateModelRequest)(nil),   // 6: webitel.kb.UpdateModelRequest
	(*DeleteModelRequest)(nil),   // 7: webitel.kb.DeleteModelRequest
	(*ValidateModelRequest)(nil), // 8: webitel.kb.ValidateModelRequest
	(*Lookup)(nil),               // 9: general.Lookup
}
var file_model_proto_depIdxs = []int32{
	9,  // 0: webitel.kb.EmbeddingModel.created_by:type_name -> general.Lookup
	0,  // 1: webitel.kb.EmbeddingModelList.items:type_name -> webitel.kb.EmbeddingModel
	1,  // 2: webitel.kb.CreateModelRequest.input:type_name -> webitel.kb.InputEmbeddingModel
	1,  // 3: webitel.kb.UpdateModelRequest.input:type_name -> webitel.kb.InputEmbeddingModel
	2,  // 4: webitel.kb.EmbeddingModels.ListModels:input_type -> webitel.kb.ListModelsRequest
	4,  // 5: webitel.kb.EmbeddingModels.LocateModel:input_type -> webitel.kb.LocateModelRequest
	5,  // 6: webitel.kb.EmbeddingModels.CreateModel:input_type -> webitel.kb.CreateModelRequest
	6,  // 7: webitel.kb.EmbeddingModels.UpdateModel:input_type -> webitel.kb.UpdateModelRequest
	7,  // 8: webitel.kb.EmbeddingModels.DeleteModel:input_type -> webitel.kb.DeleteModelRequest
	8,  // 9: webitel.kb.EmbeddingModels.ValidateModel:input_type -> webitel.kb.ValidateModelRequest
	3,  // 10: webitel.kb.EmbeddingModels.ListModels:output_type -> webitel.kb.EmbeddingModelList
	0,  // 11: webitel.kb.EmbeddingModels.LocateModel:output_type -> webitel.kb.EmbeddingModel
	0,  // 12: webitel.kb.EmbeddingModels.CreateModel:output_type -> webitel.kb.EmbeddingModel
	0,  // 13: webitel.kb.EmbeddingModels.UpdateModel:output_type -> webitel.kb.EmbeddingModel
	0,  // 14: webitel.kb.EmbeddingModels.DeleteModel:output_type -> webitel.kb.EmbeddingModel
	0,  // 15: webitel.kb.EmbeddingModels.ValidateModel:output_type -> webitel.kb.EmbeddingModel
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_rawDesc), len(file_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
