// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: model.proto

package kb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmbeddingModels_ListModels_FullMethodName    = "/webitel.kb.EmbeddingModels/ListModels"
	EmbeddingModels_LocateModel_FullMethodName   = "/webitel.kb.EmbeddingModels/LocateModel"
	EmbeddingModels_CreateModel_FullMethodName   = "/webitel.kb.EmbeddingModels/CreateModel"
	EmbeddingModels_UpdateModel_FullMethodName   = "/webitel.kb.EmbeddingModels/UpdateModel"
	EmbeddingModels_DeleteModel_FullMethodName   = "/webitel.kb.EmbeddingModels/DeleteModel"
	EmbeddingModels_ValidateModel_FullMethodName = "/webitel.kb.EmbeddingModels/ValidateModel"
)

// EmbeddingModelsClient is the client API for EmbeddingModels service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmbeddingModels manages the registry of embedding and reranker models.
// The encrypted provider credential is never returned; it is set via api_key
// on input and validated by a test call before a space may select the model.
type EmbeddingModelsClient interface {
	// ListModels returns models available to the caller's domain (and globals).
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*EmbeddingModelList, error)
	// LocateModel returns a single model by id.
	LocateModel(ctx context.Context, in *LocateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error)
	// CreateModel registers a new model.
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error)
	// UpdateModel updates a model registration.
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error)
	// DeleteModel removes a model registration.
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error)
	// ValidateModel runs a test embed/rerank call and stamps validated_at on success.
	ValidateModel(ctx context.Context, in *ValidateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error)
}

type embeddingModelsClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingModelsClient(cc grpc.ClientConnInterface) EmbeddingModelsClient {
	return &embeddingModelsClient{cc}
}

func (c *embeddingModelsClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*EmbeddingModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingModelList)
	err := c.cc.Invoke(ctx, EmbeddingModels_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingModelsClient) LocateModel(ctx context.Context, in *LocateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingModel)
	err := c.cc.Invoke(ctx, EmbeddingModels_LocateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingModelsClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingModel)
	err := c.cc.Invoke(ctx, EmbeddingModels_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingModelsClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingModel)
	err := c.cc.Invoke(ctx, EmbeddingModels_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingModelsClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingModel)
	err := c.cc.Invoke(ctx, EmbeddingModels_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *embeddingModelsClient) ValidateModel(ctx context.Context, in *ValidateModelRequest, opts ...grpc.CallOption) (*EmbeddingModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingModel)
	err := c.cc.Invoke(ctx, EmbeddingModels_ValidateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingModelsServer is the server API for EmbeddingModels service.
// All implementations must embed UnimplementedEmbeddingModelsServer
// for forward compatibility.
//
// EmbeddingModels manages the registry of embedding and reranker models.
// The encrypted provider credential is never returned; it is set via api_key
// on input and validated by a test call before a space may select the model.
type EmbeddingModelsServer interface {
	// ListModels returns models available to the caller's domain (and globals).
	ListModels(context.Context, *ListModelsRequest) (*EmbeddingModelList, error)
	// LocateModel returns a single model by id.
	LocateModel(context.Context, *LocateModelRequest) (*EmbeddingModel, error)
	// CreateModel registers a new model.
	CreateModel(context.Context, *CreateModelRequest) (*EmbeddingModel, error)
	// UpdateModel updates a model registration.
	UpdateModel(context.Context, *UpdateModelRequest) (*EmbeddingModel, error)
	// DeleteModel removes a model registration.
	DeleteModel(context.Context, *DeleteModelRequest) (*EmbeddingModel, error)
	// ValidateModel runs a test embed/rerank call and stamps validated_at on success.
	ValidateModel(context.Context, *ValidateModelRequest) (*EmbeddingModel, error)
	mustEmbedUnimplementedEmbeddingModelsServer()
}

// UnimplementedEmbeddingModelsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbeddingModelsServer struct{}

func (UnimplementedEmbeddingModelsServer) ListModels(context.Context, *ListModelsRequest) (*EmbeddingModelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedEmbeddingModelsServer) LocateModel(context.Context, *LocateModelRequest) (*EmbeddingModel, error) {
	return nil, status.Error(codes.Unimplemented, "method LocateModel not implemented")
}
func (UnimplementedEmbeddingModelsServer) CreateModel(context.Context, *CreateModelRequest) (*EmbeddingModel, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedEmbeddingModelsServer) UpdateModel(context.Context, *UpdateModelRequest) (*EmbeddingModel, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedEmbeddingModelsServer) DeleteModel(context.Context, *DeleteModelRequest) (*EmbeddingModel, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedEmbeddingModelsServer) ValidateModel(context.Context, *ValidateModelRequest) (*EmbeddingModel, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateModel not implemented")
}
func (UnimplementedEmbeddingModelsServer) mustEmbedUnimplementedEmbeddingModelsServer() {}
func (UnimplementedEmbeddingModelsServer) testEmbeddedByValue()                         {}

// UnsafeEmbeddingModelsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingModelsServer will
// result in compilation errors.
type UnsafeEmbeddingModelsServer interface {
	mustEmbedUnimplementedEmbeddingModelsServer()
}

func RegisterEmbeddingModelsServer(s grpc.ServiceRegistrar, srv EmbeddingModelsServer) {
	// If the following call panics, it indicates UnimplementedEmbeddingModelsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmbeddingModels_ServiceDesc, srv)
}

func _EmbeddingModels_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingModelsServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingModels_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingModelsServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingModels_LocateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingModelsServer).LocateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingModels_LocateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingModelsServer).LocateModel(ctx, req.(*LocateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingModels_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingModelsServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingModels_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingModelsServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingModels_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingModelsServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingModels_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingModelsServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingModels_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingModelsServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingModels_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingModelsServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmbeddingModels_ValidateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingModelsServer).ValidateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingModels_ValidateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingModelsServer).ValidateModel(ctx, req.(*ValidateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingModels_ServiceDesc is the grpc.ServiceDesc for EmbeddingModels service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingModels_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webitel.kb.EmbeddingModels",
	HandlerType: (*EmbeddingModelsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _EmbeddingModels_ListModels_Handler,
		},
		{
			MethodName: "LocateModel",
			Handler:    _EmbeddingModels_LocateModel_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _EmbeddingModels_CreateModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _EmbeddingModels_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _EmbeddingModels_DeleteModel_Handler,
		},
		{
			MethodName: "ValidateModel",
			Handler:    _EmbeddingModels_ValidateModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}
