// Code generated by protoc-gen-go-webitel. DO NOT EDIT.
// versions:
// - protoc-gen-go-webitel v1.0.0
// - protoc                (unknown)

package kb

// WebitelServicesInfo is the list of services defined in proto files.
type WebitelServicesInfo map[string]WebitelServices

type WebitelServices struct {
	ObjClass           string
	AdditionalLicenses []string
	WebitelMethods     map[string]WebitelMethod
}

// WebitelMethod is the list of methods defined in this service.
type WebitelMethod struct {
	HttpBindings []*HttpBinding
	Access       int
	Input        string
	Output       string
}

type HttpBinding struct {
	Path   string
	Method string
}

var WebitelAPI = WebitelServicesInfo{
	"Articles": WebitelServices{
		ObjClass:           "kb_articles",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListArticles": WebitelMethod{
				Access: 1,
				Input:  "ListArticlesRequest",
				Output: "ArticleList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles",
						Method: "GET",
					},
				},
			},
			"LocateArticle": WebitelMethod{
				Access: 1,
				Input:  "LocateArticleRequest",
				Output: "Article",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{etag}",
						Method: "GET",
					},
				},
			},
			"CreateArticle": WebitelMethod{
				Access: 2,
				Input:  "CreateArticleRequest",
				Output: "Article",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles",
						Method: "POST",
					},
				},
			},
			"UpdateArticle": WebitelMethod{
				Access: 2,
				Input:  "UpdateArticleRequest",
				Output: "Article",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{etag}",
						Method: "PUT",
					},
					{
						Path:   "/v1/kb/articles/{etag}",
						Method: "PATCH",
					},
				},
			},
			"DeleteArticle": WebitelMethod{
				Access: 2,
				Input:  "DeleteArticleRequest",
				Output: "Article",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{etag}",
						Method: "DELETE",
					},
				},
			},
			"MoveArticle": WebitelMethod{
				Access: 2,
				Input:  "MoveArticleRequest",
				Output: "Article",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{etag}/move",
						Method: "POST",
					},
				},
			},
			"ListChildren": WebitelMethod{
				Access: 1,
				Input:  "ListChildrenRequest",
				Output: "ArticleList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{id}/children",
						Method: "GET",
					},
				},
			},
			"ListAncestors": WebitelMethod{
				Access: 1,
				Input:  "ListAncestorsRequest",
				Output: "ArticleList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{id}/ancestors",
						Method: "GET",
					},
				},
			},
			"GetTree": WebitelMethod{
				Access: 1,
				Input:  "GetTreeRequest",
				Output: "GetTreeResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces/{space_id}/tree",
						Method: "GET",
					},
				},
			},
		},
	},
	"Attachments": WebitelServices{
		ObjClass:           "kb_articles",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListFiles": WebitelMethod{
				Access: 1,
				Input:  "ListFilesRequest",
				Output: "FileList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{article_etag}/files",
						Method: "GET",
					},
				},
			},
			"DeleteFile": WebitelMethod{
				Access: 2,
				Input:  "DeleteFileRequest",
				Output: "File",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{article_etag}/files/{id}",
						Method: "DELETE",
					},
				},
			},
		},
	},
	"EmbeddingModels": WebitelServices{
		ObjClass:           "kb_models",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListModels": WebitelMethod{
				Access: 1,
				Input:  "ListModelsRequest",
				Output: "EmbeddingModelList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/models",
						Method: "GET",
					},
				},
			},
			"LocateModel": WebitelMethod{
				Access: 1,
				Input:  "LocateModelRequest",
				Output: "EmbeddingModel",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/models/{id}",
						Method: "GET",
					},
				},
			},
			"CreateModel": WebitelMethod{
				Access: 2,
				Input:  "CreateModelRequest",
				Output: "EmbeddingModel",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/models",
						Method: "POST",
					},
				},
			},
			"UpdateModel": WebitelMethod{
				Access: 2,
				Input:  "UpdateModelRequest",
				Output: "EmbeddingModel",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/models/{id}",
						Method: "PUT",
					},
					{
						Path:   "/v1/kb/models/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteModel": WebitelMethod{
				Access: 2,
				Input:  "DeleteModelRequest",
				Output: "EmbeddingModel",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/models/{id}",
						Method: "DELETE",
					},
				},
			},
			"ValidateModel": WebitelMethod{
				Access: 2,
				Input:  "ValidateModelRequest",
				Output: "EmbeddingModel",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/models/{id}/validate",
						Method: "POST",
					},
				},
			},
		},
	},
	"Retrieval": WebitelServices{
		ObjClass:           "kb_articles",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"Search": WebitelMethod{
				Access: 1,
				Input:  "SearchRequest",
				Output: "SearchResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/search",
						Method: "GET",
					},
				},
			},
			"Resolve": WebitelMethod{
				Access: 1,
				Input:  "ResolveRequest",
				Output: "ResolveResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/resolve",
						Method: "POST",
					},
				},
			},
			"SemanticSearch": WebitelMethod{
				Access: 1,
				Input:  "SemanticSearchRequest",
				Output: "SemanticSearchResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/semantic_search",
						Method: "POST",
					},
				},
			},
			"Suggest": WebitelMethod{
				Access: 1,
				Input:  "SuggestRequest",
				Output: "SuggestResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/suggest",
						Method: "POST",
					},
				},
			},
			"Menu": WebitelMethod{
				Access: 1,
				Input:  "MenuRequest",
				Output: "MenuResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces/{space_id}/articles",
						Method: "GET",
					},
				},
			},
		},
	},
	"Spaces": WebitelServices{
		ObjClass:           "kb_spaces",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListSpaces": WebitelMethod{
				Access: 1,
				Input:  "ListSpacesRequest",
				Output: "SpaceList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces",
						Method: "GET",
					},
				},
			},
			"LocateSpace": WebitelMethod{
				Access: 1,
				Input:  "LocateSpaceRequest",
				Output: "Space",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces/{id}",
						Method: "GET",
					},
				},
			},
			"CreateSpace": WebitelMethod{
				Access: 2,
				Input:  "CreateSpaceRequest",
				Output: "Space",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces",
						Method: "POST",
					},
				},
			},
			"UpdateSpace": WebitelMethod{
				Access: 2,
				Input:  "UpdateSpaceRequest",
				Output: "Space",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces/{id}",
						Method: "PUT",
					},
					{
						Path:   "/v1/kb/spaces/{id}",
						Method: "PATCH",
					},
				},
			},
			"DeleteSpace": WebitelMethod{
				Access: 2,
				Input:  "DeleteSpaceRequest",
				Output: "Space",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces/{id}",
						Method: "DELETE",
					},
				},
			},
		},
	},
	"Tags": WebitelServices{
		ObjClass:           "kb_articles",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"SuggestTags": WebitelMethod{
				Access: 1,
				Input:  "SuggestTagsRequest",
				Output: "SuggestTagsResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/spaces/{space_id}/tags",
						Method: "GET",
					},
				},
			},
		},
	},
	"Versions": WebitelServices{
		ObjClass:           "kb_articles",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"ListVersions": WebitelMethod{
				Access: 1,
				Input:  "ListVersionsRequest",
				Output: "ArticleVersionList",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{article_id}/versions",
						Method: "GET",
					},
				},
			},
			"GetVersion": WebitelMethod{
				Access: 1,
				Input:  "GetVersionRequest",
				Output: "ArticleVersion",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{article_id}/versions/{version_number}",
						Method: "GET",
					},
				},
			},
			"RestoreVersion": WebitelMethod{
				Access: 2,
				Input:  "RestoreVersionRequest",
				Output: "ArticleVersion",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/v1/kb/articles/{article_id}/versions/{version_number}/restore",
						Method: "POST",
					},
				},
			},
		},
	},
}
