// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: retrieval.proto

package kb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tag-filter combination mode.
type TagMatch int32

const (
	// Default: match articles having ALL listed tags (AND).
	TagMatch_TAG_MATCH_ALL TagMatch = 0
	// Match articles having ANY listed tag (OR).
	TagMatch_TAG_MATCH_ANY TagMatch = 1
)

// Enum value maps for TagMatch.
var (
	TagMatch_name = map[int32]string{
		0: "TAG_MATCH_ALL",
		1: "TAG_MATCH_ANY",
	}
	TagMatch_value = map[string]int32{
		"TAG_MATCH_ALL": 0,
		"TAG_MATCH_ANY": 1,
	}
)

func (x TagMatch) Enum() *TagMatch {
	p := new(TagMatch)
	*p = x
	return p
}

func (x TagMatch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagMatch) Descriptor() protoreflect.EnumDescriptor {
	return file_retrieval_proto_enumTypes[0].Descriptor()
}

func (TagMatch) Type() protoreflect.EnumType {
	return &file_retrieval_proto_enumTypes[0]
}

func (x TagMatch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagMatch.Descriptor instead.
func (TagMatch) EnumDescriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{0}
}

// SearchRequest parameters for full-text search.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Free-text query.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Spaces to search within.
	SpaceIds []int64 `protobuf:"varint,2,rep,packed,name=space_ids,json=spaceIds,proto3" json:"space_ids,omitempty"`
	// Optional tag filter.
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// How to combine the tag filter.
	TagMatch TagMatch `protobuf:"varint,4,opt,name=tag_match,json=tagMatch,proto3,enum=webitel.kb.TagMatch" json:"tag_match,omitempty"`
	// Page size.
	Size int32 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// Page number (1-based).
	Page          int32 `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_retrieval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetSpaceIds() []int64 {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

func (x *SearchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchRequest) GetTagMatch() TagMatch {
	if x != nil {
		return x.TagMatch
	}
	return TagMatch_TAG_MATCH_ALL
}

func (x *SearchRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// SearchResponse is a page of article summaries.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matched article summaries.
	Items []*ArticleSummary `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether a next page exists.
	Next          bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_retrieval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetItems() []*ArticleSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResponse) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// ResolveRequest selects articles by id within the given spaces.
type ResolveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Article ids to resolve.
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	// Spaces the ids are expected in (RBAC scope).
	SpaceIds      []int64 `protobuf:"varint,2,rep,packed,name=space_ids,json=spaceIds,proto3" json:"space_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_retrieval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ResolveRequest) GetSpaceIds() []int64 {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

// ResolveResponse returns the resolved article summaries.
type ResolveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved article summaries (RBAC filtered).
	Items         []*ArticleSummary `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_retrieval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResponse) GetItems() []*ArticleSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

// SemanticSearchRequest parameters for hybrid retrieval.
type SemanticSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Natural-language query (e.g. STT transcript).
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Spaces to search within (bot service scope).
	SpaceIds []int64 `protobuf:"varint,2,rep,packed,name=space_ids,json=spaceIds,proto3" json:"space_ids,omitempty"`
	// Maximum number of chunks to return.
	TopK int32 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// Whether to include structured citations.
	IncludeCitations bool `protobuf:"varint,4,opt,name=include_citations,json=includeCitations,proto3" json:"include_citations,omitempty"`
	// Optional tag filter.
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// How to combine the tag filter.
	TagMatch      TagMatch `protobuf:"varint,6,opt,name=tag_match,json=tagMatch,proto3,enum=webitel.kb.TagMatch" json:"tag_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_retrieval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{4}
}

func (x *SemanticSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SemanticSearchRequest) GetSpaceIds() []int64 {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

func (x *SemanticSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SemanticSearchRequest) GetIncludeCitations() bool {
	if x != nil {
		return x.IncludeCitations
	}
	return false
}

func (x *SemanticSearchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SemanticSearchRequest) GetTagMatch() TagMatch {
	if x != nil {
		return x.TagMatch
	}
	return TagMatch_TAG_MATCH_ALL
}

// SemanticSearchResponse returns ranked chunks and optional citations.
type SemanticSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Top-K ranked chunks.
	Chunks []*Chunk `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Structured citations (empty unless requested).
	Citations     []*Citation `protobuf:"bytes,2,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_retrieval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{5}
}

func (x *SemanticSearchResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SemanticSearchResponse) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

// SuggestRequest parameters for operator assist.
type SuggestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latest customer message used as the query.
	CustomerMessage string `protobuf:"bytes,1,opt,name=customer_message,json=customerMessage,proto3" json:"customer_message,omitempty"`
	// Spaces to search within.
	SpaceIds []int64 `protobuf:"varint,2,rep,packed,name=space_ids,json=spaceIds,proto3" json:"space_ids,omitempty"`
	// Operator team id (team binding scope).
	TeamId int64 `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// When true return chunks instead of article summaries.
	ReturnChunks  bool `protobuf:"varint,4,opt,name=return_chunks,json=returnChunks,proto3" json:"return_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_retrieval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{6}
}

func (x *SuggestRequest) GetCustomerMessage() string {
	if x != nil {
		return x.CustomerMessage
	}
	return ""
}

func (x *SuggestRequest) GetSpaceIds() []int64 {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

func (x *SuggestRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *SuggestRequest) GetReturnChunks() bool {
	if x != nil {
		return x.ReturnChunks
	}
	return false
}

// SuggestResponse returns reranked suggestions.
type SuggestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Suggested article summaries.
	Articles []*ArticleSummary `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	// Suggested chunks for draft generation.
	Chunks        []*Chunk `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_retrieval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestResponse) GetArticles() []*ArticleSummary {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *SuggestResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// MenuRequest parameters for bot menus.
type MenuRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space to read from.
	SpaceId int64 `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Parent article id; 0 for top level.
	ParentId int64 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Maximum hierarchy depth to return.
	DepthLimit    int32 `protobuf:"varint,3,opt,name=depth_limit,json=depthLimit,proto3" json:"depth_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_retrieval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{8}
}

func (x *MenuRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *MenuRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *MenuRequest) GetDepthLimit() int32 {
	if x != nil {
		return x.DepthLimit
	}
	return 0
}

// MenuResponse returns child articles for menu rendering.
type MenuResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Child article summaries (FAQ children include body inline).
	Items         []*ArticleSummary `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_retrieval_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_proto_rawDescGZIP(), []int{9}
}

func (x *MenuResponse) GetItems() []*ArticleSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_retrieval_proto protoreflect.FileDescriptor

const file_retrieval_proto_rawDesc = "" +
	"\n" +
	"\x0fretrieval.proto\x12\n" +
	"webitel.kb\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xb1\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tspace_ids\x18\x02 \x03(\x03R\bspaceIds\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x121\n" +
	"\ttag_match\x18\x04 \x01(\x0e2\x14.webitel.kb.TagMatchR\btagMatch\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\"V\n" +
	"\x0eSearchResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.webitel.kb.ArticleSummaryR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\"?\n" +
	"\x0eResolveRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x1b\n" +
	"\tspace_ids\x18\x02 \x03(\x03R\bspaceIds\"C\n" +
	"\x0fResolveResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.webitel.kb.ArticleSummaryR\x05items\"\xd3\x01\n" +
	"\x15SemanticSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tspace_ids\x18\x02 \x03(\x03R\bspaceIds\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12+\n" +
	"\x11include_citations\x18\x04 \x01(\bR\x10includeCitations\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x121\n" +
	"\ttag_match\x18\x06 \x01(\x0e2\x14.webitel.kb.TagMatchR\btagMatch\"w\n" +
	"\x16SemanticSearchResponse\x12)\n" +
	"\x06chunks\x18\x01 \x03(\v2\x11.webitel.kb.ChunkR\x06chunks\x122\n" +
	"\tcitations\x18\x02 \x03(\v2\x14.webitel.kb.CitationR\tcitations\"\x96\x01\n" +
	"\x0eSuggestRequest\x12)\n" +
	"\x10customer_message\x18\x01 \x01(\tR\x0fcustomerMessage\x12\x1b\n" +
	"\tspace_ids\x18\x02 \x03(\x03R\bspaceIds\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\x03R\x06teamId\x12#\n" +
	"\rreturn_chunks\x18\x04 \x01(\bR\freturnChunks\"t\n" +
	"\x0fSuggestResponse\x126\n" +
	"\barticles\x18\x01 \x03(\v2\x1a.webitel.kb.ArticleSummaryR\barticles\x12)\n" +
	"\x06chunks\x18\x02 \x03(\v2\x11.webitel.kb.ChunkR\x06chunks\"f\n" +
	"\vMenuRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\x03R\aspaceId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x1f\n" +
	"\vdepth_limit\x18\x03 \x01(\x05R\n" +
	"depthLimit\"@\n" +
	"\fMenuResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.webitel.kb.ArticleSummaryR\x05items*0\n" +
	"\bTagMatch\x12\x11\n" +
	"\rTAG_MATCH_ALL\x10\x00\x12\x11\n" +
	"\rTAG_MATCH_ANY\x10\x012\xcd\x04\n" +
	"\tRetrieval\x12c\n" +
	"\x06Search\x12\x19.webitel.kb.SearchRequest\x1a\x1a.webitel.kb.SearchResponse\"\"\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/kb/articles/search\x12j\n" +
	"\aResolve\x12\x1a.webitel.kb.ResolveRequest\x1a\x1b.webitel.kb.ResolveResponse\"&\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/kb/articles/resolve\x12\x87\x01\n" +
	"\x0eSemanticSearch\x12!.webitel.kb.SemanticSearchRequest\x1a\".webitel.kb.SemanticSearchResponse\".\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/kb/articles/semantic_search\x12j\n" +
	"\aSuggest\x12\x1a.webitel.kb.SuggestRequest\x1a\x1b.webitel.kb.SuggestResponse\"&\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/kb/articles/suggest\x12h\n" +
	"\x04Menu\x12\x17.webitel.kb.MenuRequest\x1a\x18.webitel.kb.MenuResponse\"-\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02#\x12!/v1/kb/spaces/{space_id}/articles\x1a\x0f\x8a\xb5\x18\vkb_articlesB\x92\x01\n" +
	"\x0ecom.webitel.kbB\x0eRetrievalProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_retrieval_proto_rawDescOnce sync.Once
	file_retrieval_proto_rawDescData []byte
)

func file_retrieval_proto_rawDescGZIP() []byte {
	file_retrieval_proto_rawDescOnce.Do(func() {
		file_retrieval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_retrieval_proto_rawDesc), len(file_retrieval_proto_rawDesc)))
	})
	return file_retrieval_proto_rawDescData
}

var file_retrieval_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_retrieval_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_retrieval_proto_goTypes = []any{
	(TagMatch)(0),                  // 0: webitel.kb.TagMatch
	(*SearchRequest)(nil),          // 1: webitel.kb.SearchRequest
	(*SearchResponse)(nil),         // 2: webitel.kb.SearchResponse
	(*ResolveRequest)(nil),         // 3: webitel.kb.ResolveRequest
	(*ResolveResponse)(nil),        // 4: webitel.kb.ResolveResponse
	(*SemanticSearchRequest)(nil),  // 5: webitel.kb.SemanticSearchRequest
	(*SemanticSearchResponse)(nil), // 6: webitel.kb.SemanticSearchResponse
	(*SuggestRequest)(nil),         // 7: webitel.kb.SuggestRequest
	(*SuggestResponse)(nil),        // 8: webitel.kb.SuggestResponse
	(*MenuRequest)(nil),            // 9: webitel.kb.MenuRequest
	(*MenuResponse)(nil),           // 10: webitel.kb.MenuResponse
	(*ArticleSummary)(nil),         // 11: webitel.kb.ArticleSummary
	(*Chunk)(nil),                  // 12: webitel.kb.Chunk
	(*Citation)(nil),               // 13: webitel.kb.Citation
}
var file_retrieval_proto_depIdxs = []int32{
	0,  // 0: webitel.kb.SearchRequest.tag_match:type_name -> webitel.kb.TagMatch
	11, // 1: webitel.kb.SearchResponse.items:type_name -> webitel.kb.ArticleSummary
	11, // 2: webitel.kb.ResolveResponse.items:type_name -> webitel.kb.ArticleSummary
	0,  // 3: webitel.kb.SemanticSearchRequest.tag_match:type_name -> webitel.kb.TagMatch
	12, // 4: webitel.kb.SemanticSearchResponse.chunks:type_name -> webitel.kb.Chunk
	13, // 5: webitel.kb.SemanticSearchResponse.citations:type_name -> webitel.kb.Citation
	11, // 6: webitel.kb.SuggestResponse.articles:type_name -> webitel.kb.ArticleSummary
	12, // 7: webitel.kb.SuggestResponse.chunks:type_name -> webitel.kb.Chunk
	11, // 8: webitel.kb.MenuResponse.items:type_name -> webitel.kb.ArticleSummary
	1,  // 9: webitel.kb.Retrieval.Search:input_type -> webitel.kb.SearchRequest
	3,  // 10: webitel.kb.Retrieval.Resolve:input_type -> webitel.kb.ResolveRequest
	5,  // 11: webitel.kb.Retrieval.SemanticSearch:input_type -> webitel.kb.SemanticSearchRequest
	7,  // 12: webitel.kb.Retrieval.Suggest:input_type -> webitel.kb.SuggestRequest
	9,  // 13: webitel.kb.Retrieval.Menu:input_type -> webitel.kb.MenuRequest
	2,  // 14: webitel.kb.Retrieval.Search:output_type -> webitel.kb.SearchResponse
	4,  // 15: webitel.kb.Retrieval.Resolve:output_type -> webitel.kb.ResolveResponse
	6,  // 16: webitel.kb.Retrieval.SemanticSearch:output_type -> webitel.kb.SemanticSearchResponse
	8,  // 17: webitel.kb.Retrieval.Suggest:output_type -> webitel.kb.SuggestResponse
	10, // 18: webitel.kb.Retrieval.Menu:output_type -> webitel.kb.MenuResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_retrieval_proto_init() }
func file_retrieval_proto_init() {
	if File_retrieval_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_retrieval_proto_rawDesc), len(file_retrieval_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_retrieval_proto_goTypes,
		DependencyIndexes: file_retrieval_proto_depIdxs,
		EnumInfos:         file_retrieval_proto_enumTypes,
		MessageInfos:      file_retrieval_proto_msgTypes,
	}.Build()
	File_retrieval_proto = out.File
	file_retrieval_proto_goTypes = nil
	file_retrieval_proto_depIdxs = nil
}
