// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: space.proto

package kb

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Space is a knowledge-base space read model.
type Space struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the space.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning domain id.
	DomainId int64 `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// Human-readable name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Free-text description.
	Description string `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	// Space language; immutable, drives full-text config and retrieval.
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	// Active embedding model id (kind=embedding).
	EmbeddingModelId int64 `protobuf:"varint,5,opt,name=embedding_model_id,json=embeddingModelId,proto3" json:"embedding_model_id,omitempty"`
	// Target embedding model id for a pending model migration.
	TargetEmbeddingModelId int64 `protobuf:"varint,6,opt,name=target_embedding_model_id,json=targetEmbeddingModelId,proto3" json:"target_embedding_model_id,omitempty"`
	// Reranker model id (kind=reranker).
	RerankerModelId int64 `protobuf:"varint,7,opt,name=reranker_model_id,json=rerankerModelId,proto3" json:"reranker_model_id,omitempty"`
	// Whether articles in this space are embedded for vector search.
	VectorSearchEnabled bool `protobuf:"varint,8,opt,name=vector_search_enabled,json=vectorSearchEnabled,proto3" json:"vector_search_enabled,omitempty"`
	// Whether reranking is applied (default off, on for suggest).
	RerankEnabled bool `protobuf:"varint,9,opt,name=rerank_enabled,json=rerankEnabled,proto3" json:"rerank_enabled,omitempty"`
	// Chunking strategy identifier.
	ChunkingStrategy string `protobuf:"bytes,10,opt,name=chunking_strategy,json=chunkingStrategy,proto3" json:"chunking_strategy,omitempty"`
	// Article used as the space home page; 0 if unset.
	HomeArticleId int64 `protobuf:"varint,11,opt,name=home_article_id,json=homeArticleId,proto3" json:"home_article_id,omitempty"`
	// CreatedAt timestamp (epoch ms).
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt timestamp (epoch ms).
	UpdatedAt int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// User who created the space.
	CreatedBy *Lookup `protobuf:"bytes,22,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// User who last updated the space.
	UpdatedBy     *Lookup `protobuf:"bytes,23,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_space_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{0}
}

func (x *Space) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Space) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Space) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Space) GetEmbeddingModelId() int64 {
	if x != nil {
		return x.EmbeddingModelId
	}
	return 0
}

func (x *Space) GetTargetEmbeddingModelId() int64 {
	if x != nil {
		return x.TargetEmbeddingModelId
	}
	return 0
}

func (x *Space) GetRerankerModelId() int64 {
	if x != nil {
		return x.RerankerModelId
	}
	return 0
}

func (x *Space) GetVectorSearchEnabled() bool {
	if x != nil {
		return x.VectorSearchEnabled
	}
	return false
}

func (x *Space) GetRerankEnabled() bool {
	if x != nil {
		return x.RerankEnabled
	}
	return false
}

func (x *Space) GetChunkingStrategy() string {
	if x != nil {
		return x.ChunkingStrategy
	}
	return ""
}

func (x *Space) GetHomeArticleId() int64 {
	if x != nil {
		return x.HomeArticleId
	}
	return 0
}

func (x *Space) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Space) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Space) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Space) GetUpdatedBy() *Lookup {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

// InputSpace carries the writable fields of a space.
type InputSpace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Free-text description.
	Description string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	// Space language; immutable after creation.
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Active embedding model id.
	EmbeddingModelId int64 `protobuf:"varint,3,opt,name=embedding_model_id,json=embeddingModelId,proto3" json:"embedding_model_id,omitempty"`
	// Reranker model id.
	RerankerModelId int64 `protobuf:"varint,4,opt,name=reranker_model_id,json=rerankerModelId,proto3" json:"reranker_model_id,omitempty"`
	// Whether articles are embedded for vector search.
	VectorSearchEnabled bool `protobuf:"varint,5,opt,name=vector_search_enabled,json=vectorSearchEnabled,proto3" json:"vector_search_enabled,omitempty"`
	// Whether reranking is applied.
	RerankEnabled bool `protobuf:"varint,6,opt,name=rerank_enabled,json=rerankEnabled,proto3" json:"rerank_enabled,omitempty"`
	// Chunking strategy identifier.
	ChunkingStrategy string `protobuf:"bytes,7,opt,name=chunking_strategy,json=chunkingStrategy,proto3" json:"chunking_strategy,omitempty"`
	// Article used as the space home page.
	HomeArticleId int64 `protobuf:"varint,8,opt,name=home_article_id,json=homeArticleId,proto3" json:"home_article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputSpace) Reset() {
	*x = InputSpace{}
	mi := &file_space_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSpace) ProtoMessage() {}

func (x *InputSpace) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSpace.ProtoReflect.Descriptor instead.
func (*InputSpace) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{1}
}

func (x *InputSpace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputSpace) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InputSpace) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *InputSpace) GetEmbeddingModelId() int64 {
	if x != nil {
		return x.EmbeddingModelId
	}
	return 0
}

func (x *InputSpace) GetRerankerModelId() int64 {
	if x != nil {
		return x.RerankerModelId
	}
	return 0
}

func (x *InputSpace) GetVectorSearchEnabled() bool {
	if x != nil {
		return x.VectorSearchEnabled
	}
	return false
}

func (x *InputSpace) GetRerankEnabled() bool {
	if x != nil {
		return x.RerankEnabled
	}
	return false
}

func (x *InputSpace) GetChunkingStrategy() string {
	if x != nil {
		return x.ChunkingStrategy
	}
	return ""
}

func (x *InputSpace) GetHomeArticleId() int64 {
	if x != nil {
		return x.HomeArticleId
	}
	return 0
}

// ListSpacesRequest parameters.
type ListSpacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page size.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Page number (1-based).
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Optional name search.
	Q string `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	// Sorting criteria (e.g. field:asc).
	Sort string `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	// Set of fields to return.
	Fields        []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesRequest) Reset() {
	*x = ListSpacesRequest{}
	mi := &file_space_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesRequest) ProtoMessage() {}

func (x *ListSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesRequest.ProtoReflect.Descriptor instead.
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{2}
}

func (x *ListSpacesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListSpacesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSpacesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListSpacesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListSpacesRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// SpaceList is a page of spaces.
type SpaceList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spaces on this page.
	Items []*Space `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether a next page exists.
	Next          bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceList) Reset() {
	*x = SpaceList{}
	mi := &file_space_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceList) ProtoMessage() {}

func (x *SpaceList) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceList.ProtoReflect.Descriptor instead.
func (*SpaceList) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{3}
}

func (x *SpaceList) GetItems() []*Space {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SpaceList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// LocateSpaceRequest selects a space by id.
type LocateSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space id.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateSpaceRequest) Reset() {
	*x = LocateSpaceRequest{}
	mi := &file_space_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateSpaceRequest) ProtoMessage() {}

func (x *LocateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateSpaceRequest.ProtoReflect.Descriptor instead.
func (*LocateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{4}
}

func (x *LocateSpaceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// CreateSpaceRequest wraps the space to create.
type CreateSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space fields.
	Input         *InputSpace `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_space_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSpaceRequest) GetInput() *InputSpace {
	if x != nil {
		return x.Input
	}
	return nil
}

// UpdateSpaceRequest wraps the space id and updated fields.
type UpdateSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Updated space fields.
	Input         *InputSpace `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpaceRequest) Reset() {
	*x = UpdateSpaceRequest{}
	mi := &file_space_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpaceRequest) ProtoMessage() {}

func (x *UpdateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSpaceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSpaceRequest) GetInput() *InputSpace {
	if x != nil {
		return x.Input
	}
	return nil
}

// DeleteSpaceRequest selects a space to delete.
type DeleteSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space id.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpaceRequest) Reset() {
	*x = DeleteSpaceRequest{}
	mi := &file_space_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceRequest) ProtoMessage() {}

func (x *DeleteSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpaceRequest) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSpaceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_space_proto protoreflect.FileDescriptor

const file_space_proto_rawDesc = "" +
	"\n" +
	"\vspace.proto\x12\n" +
	"webitel.kb\x1a\rgeneral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"\xe9\x04\n" +
	"\x05Space\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12,\n" +
	"\x12embedding_model_id\x18\x05 \x01(\x03R\x10embeddingModelId\x129\n" +
	"\x19target_embedding_model_id\x18\x06 \x01(\x03R\x16targetEmbeddingModelId\x12*\n" +
	"\x11reranker_model_id\x18\a \x01(\x03R\x0frerankerModelId\x122\n" +
	"\x15vector_search_enabled\x18\b \x01(\bR\x13vectorSearchEnabled\x12%\n" +
	"\x0ererank_enabled\x18\t \x01(\bR\rrerankEnabled\x12+\n" +
	"\x11chunking_strategy\x18\n" +
	" \x01(\tR\x10chunkingStrategy\x12&\n" +
	"\x0fhome_article_id\x18\v \x01(\x03R\rhomeArticleId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x16 \x01(\v2\x0f.general.LookupR\tcreatedBy\x12.\n" +
	"\n" +
	"updated_by\x18\x17 \x01(\v2\x0f.general.LookupR\tupdatedBy\"\xe8\x02\n" +
	"\n" +
	"InputSpace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12,\n" +
	"\x12embedding_model_id\x18\x03 \x01(\x03R\x10embeddingModelId\x12*\n" +
	"\x11reranker_model_id\x18\x04 \x01(\x03R\x0frerankerModelId\x122\n" +
	"\x15vector_search_enabled\x18\x05 \x01(\bR\x13vectorSearchEnabled\x12%\n" +
	"\x0ererank_enabled\x18\x06 \x01(\bR\rrerankEnabled\x12+\n" +
	"\x11chunking_strategy\x18\a \x01(\tR\x10chunkingStrategy\x12&\n" +
	"\x0fhome_article_id\x18\b \x01(\x03R\rhomeArticleId\"u\n" +
	"\x11ListSpacesRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\"H\n" +
	"\tSpaceList\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.webitel.kb.SpaceR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\"$\n" +
	"\x12LocateSpaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x12CreateSpaceRequest\x12,\n" +
	"\x05input\x18\x01 \x01(\v2\x16.webitel.kb.InputSpaceR\x05input\"R\n" +
	"\x12UpdateSpaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12,\n" +
	"\x05input\x18\x02 \x01(\v2\x16.webitel.kb.InputSpaceR\x05input\"$\n" +
	"\x12DeleteSpaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xa5\x04\n" +
	"\x06Spaces\x12]\n" +
	"\n" +
	"ListSpaces\x12\x1d.webitel.kb.ListSpacesRequest\x1a\x15.webitel.kb.SpaceList\"\x19\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/kb/spaces\x12`\n" +
	"\vLocateSpace\x12\x1e.webitel.kb.LocateSpaceRequest\x1a\x11.webitel.kb.Space\"\x1e\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/kb/spaces/{id}\x12b\n" +
	"\vCreateSpace\x12\x1e.webitel.kb.CreateSpaceRequest\x1a\x11.webitel.kb.Space\" \x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x16:\x05input\"\r/v1/kb/spaces\x12\x84\x01\n" +
	"\vUpdateSpace\x12\x1e.webitel.kb.UpdateSpaceRequest\x1a\x11.webitel.kb.Space\"B\x90\xb5\x18\x02\x82\xd3\xe4\x93\x028:\x05inputZ\x1b:\x05input2\x12/v1/kb/spaces/{id}\x1a\x12/v1/kb/spaces/{id}\x12`\n" +
	"\vDeleteSpace\x12\x1e.webitel.kb.DeleteSpaceRequest\x1a\x11.webitel.kb.Space\"\x1e\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02\x14*\x12/v1/kb/spaces/{id}\x1a\r\x8a\xb5\x18\tkb_spacesB\x8e\x01\n" +
	"\x0ecom.webitel.kbB\n" +
	"SpaceProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_space_proto_rawDescOnce sync.Once
	file_space_proto_rawDescData []byte
)

func file_space_proto_rawDescGZIP() []byte {
	file_space_proto_rawDescOnce.Do(func() {
		file_space_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_space_proto_rawDesc), len(file_space_proto_rawDesc)))
	})
	return file_space_proto_rawDescData
}

var file_space_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_space_proto_goTypes = []any{
	(*Space)(nil),              // 0: webitel.kb.Space
	(*InputSpace)(nil),         // 1: webitel.kb.InputSpace
	(*ListSpacesRequest)(nil),  // 2: webitel.kb.ListSpacesRequest
	(*SpaceList)(nil),          // 3: webitel.kb.SpaceList
	(*LocateSpaceRequest)(nil), // 4: webitel.kb.LocateSpaceRequest
	(*CreateSpaceRequest)(nil), // 5: webitel.kb.CreateSpaceRequest
	(*UpdateSpaceRequest)(nil), // 6: webitel.kb.UpdateSpaceRequest
	(*DeleteSpaceRequest)(nil), // 7: webitel.kb.DeleteSpaceRequest
	(*Lookup)(nil),             // 8: general.Lookup
}
var file_space_proto_depIdxs = []int32{
	8,  // 0: webitel.kb.Space.created_by:type_name -> general.Lookup
	8,  // 1: webitel.kb.Space.updated_by:type_name -> general.Lookup
	0,  // 2: webitel.kb.SpaceList.items:type_name -> webitel.kb.Space
	1,  // 3: webitel.kb.CreateSpaceRequest.input:type_name -> webitel.kb.InputSpace
	1,  // 4: webitel.kb.UpdateSpaceRequest.input:type_name -> webitel.kb.InputSpace
	2,  // 5: webitel.kb.Spaces.ListSpaces:input_type -> webitel.kb.ListSpacesRequest
	4,  // 6: webitel.kb.Spaces.LocateSpace:input_type -> webitel.kb.LocateSpaceRequest
	5,  // 7: webitel.kb.Spaces.CreateSpace:input_type -> webitel.kb.CreateSpaceRequest
	6,  // 8: webitel.kb.Spaces.UpdateSpace:input_type -> webitel.kb.UpdateSpaceRequest
	7,  // 9: webitel.kb.Spaces.DeleteSpace:input_type -> webitel.kb.DeleteSpaceRequest
	3,  // 10: webitel.kb.Spaces.ListSpaces:output_type -> webitel.kb.SpaceList
	0,  // 11: webitel.kb.Spaces.LocateSpace:output_type -> webitel.kb.Space
	0,  // 12: webitel.kb.Spaces.CreateSpace:output_type -> webitel.kb.Space
	0,  // 13: webitel.kb.Spaces.UpdateSpace:output_type -> webitel.kb.Space
	0,  // 14: webitel.kb.Spaces.DeleteSpace:output_type -> webitel.kb.Space
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_space_proto_init() }
func file_space_proto_init() {
	if File_space_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_space_proto_rawDesc), len(file_space_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_proto_goTypes,
		DependencyIndexes: file_space_proto_depIdxs,
		MessageInfos:      file_space_proto_msgTypes,
	}.Build()
	File_space_proto = out.File
	file_space_proto_goTypes = nil
	file_space_proto_depIdxs = nil
}
