// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tag.proto

package kb

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SuggestTagsRequest parameters.
type SuggestTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space to read tags from.
	SpaceId int64 `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Prefix to match.
	Q string `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	// Maximum number of suggestions.
	Size          int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTagsRequest) Reset() {
	*x = SuggestTagsRequest{}
	mi := &file_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTagsRequest) ProtoMessage() {}

func (x *SuggestTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTagsRequest.ProtoReflect.Descriptor instead.
func (*SuggestTagsRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *SuggestTagsRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *SuggestTagsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SuggestTagsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// SuggestTagsResponse returns matching tags.
type SuggestTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching tags.
	Tags          []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTagsResponse) Reset() {
	*x = SuggestTagsResponse{}
	mi := &file_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTagsResponse) ProtoMessage() {}

func (x *SuggestTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTagsResponse.ProtoReflect.Descriptor instead.
func (*SuggestTagsResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

func (x *SuggestTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_tag_proto protoreflect.FileDescriptor

const file_tag_proto_rawDesc = "" +
	"\n" +
	"\ttag.proto\x12\n" +
	"webitel.kb\x1a\x1cgoogle/api/annotations.proto\x1a\x1aproto/webitel/option.proto\"Q\n" +
	"\x12SuggestTagsRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\x03R\aspaceId\x12\f\n" +
	"\x01q\x18\x02 \x01(\tR\x01q\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\")\n" +
	"\x13SuggestTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2\x92\x01\n" +
	"\x04Tags\x12y\n" +
	"\vSuggestTags\x12\x1e.webitel.kb.SuggestTagsRequest\x1a\x1f.webitel.kb.SuggestTagsResponse\")\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/kb/spaces/{space_id}/tags\x1a\x0f\x8a\xb5\x18\vkb_articlesB\x8c\x01\n" +
	"\x0ecom.webitel.kbB\bTagProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData []byte
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)))
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tag_proto_goTypes = []any{
	(*SuggestTagsRequest)(nil),  // 0: webitel.kb.SuggestTagsRequest
	(*SuggestTagsResponse)(nil), // 1: webitel.kb.SuggestTagsResponse
}
var file_tag_proto_depIdxs = []int32{
	0, // 0: webitel.kb.Tags.SuggestTags:input_type -> webitel.kb.SuggestTagsRequest
	1, // 1: webitel.kb.Tags.SuggestTags:output_type -> webitel.kb.SuggestTagsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
