// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: version.proto

package kb

import (
	_ "github.com/webitel/webitel-go-kit/cmd/protoc-gen-go-webitel/gen/go/proto/webitel"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArticleVersion is an immutable snapshot of article content.
type ArticleVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the version.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning article id.
	ArticleId int64 `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Monotonic version number within the article.
	VersionNumber int32 `protobuf:"varint,3,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	// Versioned title.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Editor document for this version.
	BodyRichText *structpb.Struct `protobuf:"bytes,5,opt,name=body_rich_text,json=bodyRichText,proto3" json:"body_rich_text,omitempty"`
	// Markdown serialization (chunking input).
	BodyMarkdown string `protobuf:"bytes,6,opt,name=body_markdown,json=bodyMarkdown,proto3" json:"body_markdown,omitempty"`
	// Plaintext serialization (full-text source).
	BodyPlain string `protobuf:"bytes,7,opt,name=body_plain,json=bodyPlain,proto3" json:"body_plain,omitempty"`
	// Version this one was restored from; 0 if authored directly.
	RestoredFrom int64 `protobuf:"varint,8,opt,name=restored_from,json=restoredFrom,proto3" json:"restored_from,omitempty"`
	// Optional author notes.
	Notes string `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	// CreatedAt timestamp (epoch ms).
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// User who authored the version.
	CreatedBy     *Lookup `protobuf:"bytes,22,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleVersion) Reset() {
	*x = ArticleVersion{}
	mi := &file_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleVersion) ProtoMessage() {}

func (x *ArticleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleVersion.ProtoReflect.Descriptor instead.
func (*ArticleVersion) Descriptor() ([]byte, []int) {
	return file_version_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleVersion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleVersion) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ArticleVersion) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *ArticleVersion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleVersion) GetBodyRichText() *structpb.Struct {
	if x != nil {
		return x.BodyRichText
	}
	return nil
}

func (x *ArticleVersion) GetBodyMarkdown() string {
	if x != nil {
		return x.BodyMarkdown
	}
	return ""
}

func (x *ArticleVersion) GetBodyPlain() string {
	if x != nil {
		return x.BodyPlain
	}
	return ""
}

func (x *ArticleVersion) GetRestoredFrom() int64 {
	if x != nil {
		return x.RestoredFrom
	}
	return 0
}

func (x *ArticleVersion) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ArticleVersion) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ArticleVersion) GetCreatedBy() *Lookup {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

// ListVersionsRequest parameters.
type ListVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning article id.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Page size.
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Page number (1-based).
	Page          int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_version_proto_rawDescGZIP(), []int{1}
}

func (x *ListVersionsRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ListVersionsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListVersionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// ArticleVersionList is a page of versions.
type ArticleVersionList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Versions on this page.
	Items []*ArticleVersion `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether a next page exists.
	Next          bool `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleVersionList) Reset() {
	*x = ArticleVersionList{}
	mi := &file_version_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleVersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleVersionList) ProtoMessage() {}

func (x *ArticleVersionList) ProtoReflect() protoreflect.Message {
	mi := &file_version_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleVersionList.ProtoReflect.Descriptor instead.
func (*ArticleVersionList) Descriptor() ([]byte, []int) {
	return file_version_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleVersionList) GetItems() []*ArticleVersion {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ArticleVersionList) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// GetVersionRequest selects a version by article and number.
type GetVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning article id.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Version number.
	VersionNumber int32 `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_version_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *GetVersionRequest) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

// RestoreVersionRequest selects a version to restore.
type RestoreVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning article id.
	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// Version number to restore.
	VersionNumber int32 `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	// Optional notes for the new version.
	Notes         string `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreVersionRequest) Reset() {
	*x = RestoreVersionRequest{}
	mi := &file_version_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreVersionRequest) ProtoMessage() {}

func (x *RestoreVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreVersionRequest.ProtoReflect.Descriptor instead.
func (*RestoreVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreVersionRequest) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *RestoreVersionRequest) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *RestoreVersionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_version_proto protoreflect.FileDescriptor

const file_version_proto_rawDesc = "" +
	"\n" +
	"\rversion.proto\x12\n" +
	"webitel.kb\x1a\rgeneral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1aproto/webitel/option.proto\"\x89\x03\n" +
	"\x0eArticleVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\x12%\n" +
	"\x0eversion_number\x18\x03 \x01(\x05R\rversionNumber\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12=\n" +
	"\x0ebody_rich_text\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fbodyRichText\x12#\n" +
	"\rbody_markdown\x18\x06 \x01(\tR\fbodyMarkdown\x12\x1d\n" +
	"\n" +
	"body_plain\x18\a \x01(\tR\tbodyPlain\x12#\n" +
	"\rrestored_from\x18\b \x01(\x03R\frestoredFrom\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12.\n" +
	"\n" +
	"created_by\x18\x16 \x01(\v2\x0f.general.LookupR\tcreatedBy\"\\\n" +
	"\x13ListVersionsRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"Z\n" +
	"\x12ArticleVersionList\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.webitel.kb.ArticleVersionR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\bR\x04next\"Y\n" +
	"\x11GetVersionRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\"s\n" +
	"\x15RestoreVersionRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x03R\tarticleId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes2\xc5\x03\n" +
	"\bVersions\x12\x7f\n" +
	"\fListVersions\x12\x1f.webitel.kb.ListVersionsRequest\x1a\x1e.webitel.kb.ArticleVersionList\".\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02$\x12\"/v1/articles/{article_id}/versions\x12\x88\x01\n" +
	"\n" +
	"GetVersion\x12\x1d.webitel.kb.GetVersionRequest\x1a\x1a.webitel.kb.ArticleVersion\"?\x90\xb5\x18\x01\x82\xd3\xe4\x93\x025\x123/v1/articles/{article_id}/versions/{version_number}\x12\x9b\x01\n" +
	"\x0eRestoreVersion\x12!.webitel.kb.RestoreVersionRequest\x1a\x1a.webitel.kb.ArticleVersion\"J\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02@:\x01*\";/v1/articles/{article_id}/versions/{version_number}/restore\x1a\x0f\x8a\xb5\x18\vkb_articlesB\x90\x01\n" +
	"\x0ecom.webitel.kbB\fVersionProtoP\x01Z'github.com/webitel/webitel-kb/api/kb;kb\xa2\x02\x03WKX\xaa\x02\n" +
	"Webitel.Kb\xca\x02\n" +
	"Webitel\\Kb\xe2\x02\x16Webitel\\Kb\\GPBMetadata\xea\x02\vWebitel::Kbb\x06proto3"

var (
	file_version_proto_rawDescOnce sync.Once
	file_version_proto_rawDescData []byte
)

func file_version_proto_rawDescGZIP() []byte {
	file_version_proto_rawDescOnce.Do(func() {
		file_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_version_proto_rawDesc), len(file_version_proto_rawDesc)))
	})
	return file_version_proto_rawDescData
}

var file_version_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_version_proto_goTypes = []any{
	(*ArticleVersion)(nil),        // 0: webitel.kb.ArticleVersion
	(*ListVersionsRequest)(nil),   // 1: webitel.kb.ListVersionsRequest
	(*ArticleVersionList)(nil),    // 2: webitel.kb.ArticleVersionList
	(*GetVersionRequest)(nil),     // 3: webitel.kb.GetVersionRequest
	(*RestoreVersionRequest)(nil), // 4: webitel.kb.RestoreVersionRequest
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*Lookup)(nil),                // 6: general.Lookup
}
var file_version_proto_depIdxs = []int32{
	5, // 0: webitel.kb.ArticleVersion.body_rich_text:type_name -> google.protobuf.Struct
	6, // 1: webitel.kb.ArticleVersion.created_by:type_name -> general.Lookup
	0, // 2: webitel.kb.ArticleVersionList.items:type_name -> webitel.kb.ArticleVersion
	1, // 3: webitel.kb.Versions.ListVersions:input_type -> webitel.kb.ListVersionsRequest
	3, // 4: webitel.kb.Versions.GetVersion:input_type -> webitel.kb.GetVersionRequest
	4, // 5: webitel.kb.Versions.RestoreVersion:input_type -> webitel.kb.RestoreVersionRequest
	2, // 6: webitel.kb.Versions.ListVersions:output_type -> webitel.kb.ArticleVersionList
	0, // 7: webitel.kb.Versions.GetVersion:output_type -> webitel.kb.ArticleVersion
	0, // 8: webitel.kb.Versions.RestoreVersion:output_type -> webitel.kb.ArticleVersion
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_version_proto_init() }
func file_version_proto_init() {
	if File_version_proto != nil {
		return
	}
	file_general_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_version_proto_rawDesc), len(file_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_version_proto_goTypes,
		DependencyIndexes: file_version_proto_depIdxs,
		MessageInfos:      file_version_proto_msgTypes,
	}.Build()
	File_version_proto = out.File
	file_version_proto_goTypes = nil
	file_version_proto_depIdxs = nil
}
