// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: indexer/indexer.proto

package kbindexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveSpaceEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       int64                  `protobuf:"varint,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSpaceEmbeddingRequest) Reset() {
	*x = ResolveSpaceEmbeddingRequest{}
	mi := &file_indexer_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSpaceEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSpaceEmbeddingRequest) ProtoMessage() {}

func (x *ResolveSpaceEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSpaceEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*ResolveSpaceEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_indexer_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveSpaceEmbeddingRequest) GetSpaceId() int64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

// SpaceEmbedding is what the worker needs to embed the chunks of a space.
type SpaceEmbedding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when the space is not embedded; every field below is then unset.
	VectorSearchEnabled bool `protobuf:"varint,1,opt,name=vector_search_enabled,json=vectorSearchEnabled,proto3" json:"vector_search_enabled,omitempty"`
	// Model the vectors are stored under (kb.chunk_embedding.model_id).
	ModelId    int64  `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Provider   string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ModelRef   string `protobuf:"bytes,4,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	Dimensions int32  `protobuf:"varint,5,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// URL of a self-hosted service; empty for cloud providers.
	Endpoint string `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Provider credential in plaintext; empty for self-hosted providers.
	ApiKey string `protobuf:"bytes,7,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Registration test call result; reported, not enforced.
	Validated     bool `protobuf:"varint,8,opt,name=validated,proto3" json:"validated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceEmbedding) Reset() {
	*x = SpaceEmbedding{}
	mi := &file_indexer_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceEmbedding) ProtoMessage() {}

func (x *SpaceEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceEmbedding.ProtoReflect.Descriptor instead.
func (*SpaceEmbedding) Descriptor() ([]byte, []int) {
	return file_indexer_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceEmbedding) GetVectorSearchEnabled() bool {
	if x != nil {
		return x.VectorSearchEnabled
	}
	return false
}

func (x *SpaceEmbedding) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *SpaceEmbedding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SpaceEmbedding) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *SpaceEmbedding) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *SpaceEmbedding) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *SpaceEmbedding) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SpaceEmbedding) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

var File_indexer_indexer_proto protoreflect.FileDescriptor

const file_indexer_indexer_proto_rawDesc = "" +
	"\n" +
	"\x15indexer/indexer.proto\x12\x12webitel.kb.indexer\"9\n" +
	"\x1cResolveSpaceEmbeddingRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\x03R\aspaceId\"\x8b\x02\n" +
	"\x0eSpaceEmbedding\x122\n" +
	"\x15vector_search_enabled\x18\x01 \x01(\bR\x13vectorSearchEnabled\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\x03R\amodelId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\tmodel_ref\x18\x04 \x01(\tR\bmodelRef\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x05 \x01(\x05R\n" +
	"dimensions\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\x17\n" +
	"\aapi_key\x18\a \x01(\tR\x06apiKey\x12\x1c\n" +
	"\tvalidated\x18\b \x01(\bR\tvalidated2y\n" +
	"\bIndexing\x12m\n" +
	"\x15ResolveSpaceEmbedding\x120.webitel.kb.indexer.ResolveSpaceEmbeddingRequest\x1a\".webitel.kb.indexer.SpaceEmbeddingB8Z6github.com/webitel/webitel-kb/api/kb/indexer;kbindexerb\x06proto3"

var (
	file_indexer_indexer_proto_rawDescOnce sync.Once
	file_indexer_indexer_proto_rawDescData []byte
)

func file_indexer_indexer_proto_rawDescGZIP() []byte {
	file_indexer_indexer_proto_rawDescOnce.Do(func() {
		file_indexer_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_indexer_proto_rawDesc), len(file_indexer_indexer_proto_rawDesc)))
	})
	return file_indexer_indexer_proto_rawDescData
}

var file_indexer_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_indexer_indexer_proto_goTypes = []any{
	(*ResolveSpaceEmbeddingRequest)(nil), // 0: webitel.kb.indexer.ResolveSpaceEmbeddingRequest
	(*SpaceEmbedding)(nil),               // 1: webitel.kb.indexer.SpaceEmbedding
}
var file_indexer_indexer_proto_depIdxs = []int32{
	0, // 0: webitel.kb.indexer.Indexing.ResolveSpaceEmbedding:input_type -> webitel.kb.indexer.ResolveSpaceEmbeddingRequest
	1, // 1: webitel.kb.indexer.Indexing.ResolveSpaceEmbedding:output_type -> webitel.kb.indexer.SpaceEmbedding
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_indexer_indexer_proto_init() }
func file_indexer_indexer_proto_init() {
	if File_indexer_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_indexer_proto_rawDesc), len(file_indexer_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexer_indexer_proto_goTypes,
		DependencyIndexes: file_indexer_indexer_proto_depIdxs,
		MessageInfos:      file_indexer_indexer_proto_msgTypes,
	}.Build()
	File_indexer_indexer_proto = out.File
	file_indexer_indexer_proto_goTypes = nil
	file_indexer_indexer_proto_depIdxs = nil
}
